### ISSUE TITLE
[Nhóm#06] - Lỗi giao diện - Lỗi văn bản bị đè lên nhau - trang http://www.http://yame.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#102]
a. Web Browser: Google Chrome Version 116.0.5845.111
b. Các bước phát hiện lỗi 
i. #1: Truy cập Yame.vn , sau đó nhấp vào mục Quy chế hoạt động ở dưới cùng
![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/2d178615-a560-4656-be02-26adb3f32689)

ii. #2: Kéo xuống mục số IX. Quyền và nghĩa vụ sẽ thấy lỗi như trên

![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/d2e7586f-e2bb-4b35-9a1e-2057dc87f424)

![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/d46e7839-ead4-42b3-9601-a861fa74e338)

c. Kết quả thực tế: Văn bản bị đè lên nhau 
d. Kết quả mong đợi: Văn bản không bị đè lên nhau

**Comment by 31211027613** [comment]
Mình thấy nó không bị đè, nó chỉ bị chạm vào nhau do kích thước của chữ in đậm lớn hơn bình thường. Nên nếu là lỗi thì chưa phải ạ
