### ISSUE TITLE
Nhóm#07] - Lỗi GUI - Lỗi các option đè lên các chức năng khác - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027625** [UEHMonQAQC/23_902#106]
a. Web Browser: Google Chrome 116.0.5845.111 ( Bản chính thức)(64bit)
b. Các bước để phát hiện lỗi:
i. #1: Chọn trình duyệt và đăng nhập vào https://khdtkt.ueh.edu.vn/
ii. #2 Sử dụng tính năng snap windows ở trang chủ
iii. #3 Chọn Menu và bảng chọn hiện ra như sau
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/e3ecc41f-1e1b-43d6-8d57-4eef8544ce01)
iv. #4 Click vào button mũi tên hiển thị thêm cạnh bên phải option kế hoạch đào tạo-tkb-lịch thi- giảng đường 
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/741bf642-32d9-42b0-b491-5a2176889dbb)
v. #5 Khung hiển thị các option con đã che mất đi các option lớn phía sau lẫn phần nội dung thông báo, các option tra cứu và phúc khảo
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/5c65b19a-1e7a-451f-b30c-1727a013cf39)
Các phần bị che là:
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/213e55ef-37b8-42ac-823a-2e594894023e)
c. Kết quả thực tế: Bị che mất các tính năng và nội dung trang khi sử dụng chức năng snap windows và cho hiện thị thêm từ option lớn
d. Kết quả mong đợi: Có thể chia thành nhiều cột để giảm bớt độ dài của bảng chọn, hoặc sau khi click vào nút hiển thị thêm( dấu mũi tên) sẽ chuyển sang 1 trang mới để hiển thị các option của bảng chọn đấy

**Comment by 31211027598** [comment]
@31211027625 Đây là do thiết kế của trang web trên trình duyệt mobile, khi nhấn hiện ra các thanh bảng chọn mới bị che nhưng ta có thể thao tác xong hoặc bấm nút mũi tên bên phải để ẩn đi.
Cũng giống như phần web khi ta trỏ chuột vào thanh bảng chọn sẽ hiện ra. khi di chuột ra ngoài sẽ biến mất.
