### ISSUE TITLE
[Nhóm#07] - Lỗi phi chức năng - Lỗi truy vấn khi trình duyệt trực tiếp thao tác với máy chủ khi giả lập 10000 người dùng - Trang https://gamevui.vn/

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#107]
a. Web Browser: Microsoft Edge Version 116.0.1938.54 (Official build) (64-bit)
b. Các bước phát hiện lỗi:
i. #1 Mở phần mềm Apache JMeter và vào file chọn temple "Building a Web Test Plan". Sau đó Create
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/4977eb4d-79a7-42e5-b1ed-d1fa795915bb)

ii. #2: Hiển thị ra được trang như vậy và sau đó đổi tên trang cho phù hợp. Và chọn số lượng người giả lập thao tác với máy chủ (ở đây mình chọn 10000 người)
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/6faf9ccb-ac63-4b9c-b847-8a6efcbd64c7)

iii. #3: Trong mục "HTTP Resquest Defaults" điền thông tin trang muốn test vào(lưu ý: do đã có protocol(http) rồi bên SeverName chỉ để tên web: 
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/945941e8-41d3-440c-b295-285405cf5ed3)

iv. #4: Ở HomePage đặt tên theo trang mà bạn test. 
Sau đó vào trang [https://gamevui.vn/](). Bấm Ctrl + U để lấy được nguồn trang. Sau đó Ctrl + A và Ctrl + C để lưu mã lại.
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/45da49c8-581f-437b-b847-93132476e381)

v. #5: Sau khi làm xong, quay lại phần mềm Apache JMeter rồi lựa chọn "Assertion" nằm trong "Home page":
Xóa nội dung mặc định trong phần "Patterns to Test" rồi nhấn "Add from Clipboard"
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/35a1c7ba-38c2-4209-9782-23f19afb9f99)

vi. #6: Sau đó lựa chọn "View Result Tree" và click vào nút "Start" hoặc Ctrl + R. Kết quả như hình dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/f262de5e-698c-47cc-b546-926e1de53a3a)

c. Kết quả thực tế: Tốc độ tải trang càng lúc chậm đi từ 4000 người trở lên, hầu hết người dùng sẽ bị lỗi 404.
d. Kết quả mong muốn: Thời gian chạy dưới 5s, tốc độ tải trang của các người dùng chạy cùng lúc, tăng được số lượng người dùng thao tác vào trang nhiều hơn nữa.

**Comment by 31211027598** [comment]
@31211027599 Mình xin lỗi do hôm đó check rất nhiều lỗi nên lỗi này mình đã quên. Lỗi này đã có bạn đăng lên trước đó rồi nên đây là lỗi bị trùng. 
Vì trực tiếp theo tác cũng giống như truy cập cùng một lúc nhiều người dùng. Link lỗi trùng bên dưới.
https://github.com/UEHMonQAQC/23_902/issues/63

**Comment by phatleework7** [comment]
okay cảm ơn bạn
