### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - Không có thẻ tối ưu hóa Progressive WebApp -  trang https://truong.hcm.edu.vn

### ISSUE THREAD

**Issue by thientruc1691997** [UEHMonQAQC/23_902#113]
- Môi trường test: Chrome MacOs
- Tool test: Lighthouse Chrome 
- Dữ liệu test: 
  +Tên trường: MN-TH-THCS-THPT Quảng Ích (qitech)
  +user: admin1
  +pass: 123456789
- Mô tả lỗi: Không có thẻ meta name="viewport", thẻ này không chỉ tối ưu hóa website cho kích thước màn hình thiết bị di động mà còn ngăn chặn độ trễ 300 mili giây khi người dùng nhập dữ liệu.

<img width="1436" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/117527214/0b8f19fa-7b4b-4129-ad56-88e43349024c">

**Comment by 31211027613** [comment]
Mình thấy trang web này nằm ngoài 2 trang web mà nhóm đã báo với mình ấy, nhóm kiểm tra lại giúp mình với nha
![QA](https://github.com/UEHMonQAQC/23_902/assets/142579142/da2ae431-7f3e-4894-a4a4-f034f2d0bb4c)

**Comment by thientruc1691997** [comment]
Chị có email cho thầy xin đổi website nhưng chưa thấy thầy phản hồi, chị có
check web mới trên semrush rồi. Tạm thời nhóm chị làm kiểm thử trên web mới
để kg ảnh hưởng đến tiến độ nha.

**Comment by 31211027613** [comment]
Dạ vâng. Nhưng mà phiền chị edit lại lỗi giúp em theo cấu trúc dưới đây với nha ạ. Em cảm ơn. 
![QA](https://github.com/UEHMonQAQC/23_902/assets/142579142/c6a53174-6c4f-412f-9a7f-372829f2fe96)

**Comment by 31211027613** [comment]
Dạ vâng. Nhưng mà phiền chị edit lại lỗi theo cấu trúc dưới đây giúp em với ạ. Em cảm ơn ạ.
![371232744_302805638963314_3507766937293861527_n](https://github.com/UEHMonQAQC/23_902/assets/142579142/38e8e810-293d-4a91-afc4-00e944d31c11)

**Comment by 31211027613** [comment]
Dạ về lỗi này, em đã gắn label nhằm do thông tin còn thiếu sót ạ, sau khi thảo luận tụi em xin kết luận lỗi trên là không phải lỗi ạ. Lý do:
1. Thẻ meta là loại thẻ k bắt buộc trong HTML
2. Nếu có thẻ này meta name="viewport", thì chỉ cho trình duyệt biết website sẽ được hiển thị thế nào, phần hiển thị phụ thuộc vào các thẻ trong body.
3. Không tìm thấy thông tin thẻ này ngăn chặn độ trễ 300 mili giây khi người dùng nhập dữ liệu.

Và cuối cùng thì tụi em xin phép không nhận xác minh lỗi từ trang web này cho đến khi thầy xác nhận nhé. Em cảm ơn và xin lỗi vì đã làm phiền ạ

**Comment by thientruc1691997** [comment]
Hi các bạn,

Mục tiêu của việc kiểm thử phi tính năng là tăng
hiệu suất, khả năng sử dụng, độ tin cậy, v.v.) của ứng dụng phần mềm. Hiện
nay các chỉ số sau khi đo đạc của website của nhóm chị như sau:
- Chị nghĩ để cải thiện các chỉ số trên thì thẻ meta này rất cần cho SEO và
giúp responsive trên thiết bị di động nha.
- Lý do số 3 mà các bạn không đồng tình là chị copy theo khuyến cáo của
Lighthouse, các bạn có thể xem hình bên dưới:

Nhờ các bạn check lại.

**Comment by 31211027613** [comment]
Dạ em chào chị, hiện tại em đang không thấy hình chị muốn gửi ạ. Cảm phiền chị giúp chúng em gửi lại hình ảnh, để tụi em có thể kiểm tra chính xác hơn ạ. Em cảm ơn rất nhiều.

**Comment by thientruc1691997** [comment]
Trên máy tính và điện thoại chị đều xem được. Tụi em muốn gửi lại qua đâu?

**Comment by 31211027613** [comment]
Dạ đây là phần hiển thị trên máy của tụi em ạ. Chị có thể gửi trực tiếp qua phần comment của Github mà không thông qua Email ạ.
![image](https://github.com/UEHMonQAQC/23_902/assets/142579142/2f1e17bc-4788-4f2c-9b36-c888694e6bec)

**Comment by thientruc1691997** [comment]
Hi các bạn, 

Mục tiêu của việc kiểm thử phi tính năng là tăng hiệu suất, khả năng sử dụng, độ tin cậy, v.v.) của ứng dụng phần mềm. Hiện nay các chỉ số sau khi đo đạc của website của nhóm chị như sau:
![image](https://github.com/UEHMonQAQC/23_902/assets/117527214/81374d3c-6900-4f54-9b58-f83641a71cfe)

- Chị nghĩ để cải thiện các chỉ số trên thì thẻ meta này rất cần cho SEO và giúp responsive trên thiết bị di động nha. 
- Lý do số 3 mà các bạn không đồng tình là chị copy theo khuyến cáo của Lighthouse, các bạn có thể xem hình bên dưới:
![image](https://github.com/UEHMonQAQC/23_902/assets/117527214/d40ccbce-ab0e-4630-89e1-b82263cc1f59)
 
Nhờ các bạn check lại.

**Comment by 31211027613** [comment]
Dạ sau khi thảo luận, xem xét các thông tin mà chị cung cấp. Tụi em đồng ý trên chính là lỗi ạ. Tụi em sẽ tính lỗi trên vào KPI khi có thông tin là thầy đã chấp nhận trang web mới ạ.

**Comment by 31211027613** [comment]
@thientruc1691997 dạ theo như ý thầy, thì lỗi này cần thêm minh chứng (thực tế hóa lỗi ngoài tools test, tận dụng lỗi đó) để xác thực, chị và các bạn xem xét sửa lại giúp em nhé
