### ISSUE TITLE
[Nhóm#04] - Lỗi giao diện - Lỗi giao diện bị mất khi phóng to trang 175% - Trang https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#115]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi phóng to trang 175%, mục "Hướng Dẫn Đặt Mua Hàng" và "Miễn Trừ Trách Nhiệm" bị khuất chữ
c. Kết quả mong muốn: Khi phóng to trang 175%, mục "Hướng Dẫn Đặt Mua Hàng" và "Miễn Trừ Trách Nhiệm"  được chia khoảng cách hợp lý, không bị che khuất.
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/148bb60b-781e-48f6-9a62-fad65fd50bf2">
ii. #1 Phóng to trang lên 175% và quan sát mục "Hướng Dẫn Đặt Mua Hàng" và "Miễn Trừ Trách Nhiệm" trên cùng
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/2bd1aea3-de75-415f-a16f-a010ff363a74">

**Comment by 31211027582** [comment]
Không được dùng chức năng zoom của trình duyệt để check lỗi Gui.
