### ISSUE TITLE
[Nhóm#07] - Lỗi GUI - Lỗi đặt địa chỉ email vào cặp thẻ <a></a> - Trang https://khdtkt.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#119]
web browser: Google Chrome
Các bước phát hiện lỗi:
#1 Ở thanh menu chọn mục liên hệ
#2 Sẽ thấy có 2 địa chỉ email được đặt vào cặp thẻ<a> </a> nhưng không có gắn link
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/3a5ac382-733c-48dd-a645-8f970aae5de6)

#3 Vì không được gắn link nên lúc ấn vào sẽ không đến địa chỉ nào hết cả, gây hiểu lầm cho người dùng
Kết quả thực tế: Đường link không dẫn đến địa chỉ nào khác
Kết quả mong đợi: nếu chỉ muốn highlight địa chỉ email cho người dùng thì không cần dùng cặp thẻ <a></a>

**Comment by 31211027598** [comment]
@31211027573 Ở đây trang dùng phương thức mailto là hợp lí, để khi nhấn vào sẽ gửi được thư điện tử.


![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/ccd0880a-ab97-4c06-90b7-1daa2c15c53b)


Ở máy mình vẫn hoạt động bình thường khi nhấn vào.


![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/8307a170-df4d-4655-9758-1c43991fd09a)
