### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi sử dụng chức năng đọc báo - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#123]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: kết quả trả chức năng đổi hiện thị “ 1 trang “ và “ 2 trang “ không hoạt động
c. Kết quả mong muốn: các chức năng đọc báo hoạt động tốt
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào Chọn biểu tượng đọc báo in và chọn bài báo bất kì
 
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/ac9948ce-e5ca-4a4b-8a3e-e24fee7a9200)

ii.#2 Chọn chế độ đọc “ 2 trang “ sau đó chuyển qua chế độ đọc “ 1 trang “ ,tuy nhiên vẫn hiện thị chế độ đọc 2 trang
 
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/005e1386-9645-4c56-90ac-3eeea24acbb1)

**Comment by 31211027582** [comment]
Trùng lỗi #36
