### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi hiển thị thời gian - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#125]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: phát hiện lỗi chức năng hiển thị thời gian không hoạt động cho đến khi refresh website
c. Kết quả mong muốn: hiển thị chính xác thời gian
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào kiểm tra “thời gian” của trang website. Lỗi hiển thị ở khung thời gian không thay đổi trừ khi refresh trang web
 
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/4a00904f-98b0-44b4-b31c-ed2fcc3b90b2)

**Comment by 31211027582** [comment]
Thời gian không thay đổi khi không refresh trang không ảnh hưởng đến chức năng chính của trang web. Chức năng chính của trang web là cho phép người đọc truy cập,  đọc bài báo, bình luận bài báo,  còn việc ghi lại thời điểm truy cập có thể hiểu là mục đích phụ.
Trong trường hợp trên, nếu trang web đọc báo không có mục đích hiển thị thời gian thực mà chỉ muốn ghi lại thời điểm bạn truy cập trang, thì việc hiển thị một thời gian cố định là hợp lý và không phải là lỗi chức năng. Điều này phụ thuộc vào thiết kế và mục đích cụ thể của trang web.
