### ISSUE TITLE
[Nhóm#04] - Lỗi giao diện - Lỗi hiển thị sai số lượng của giỏ hàng  - Trang https://caythuoc.vn/ 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#13]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi tải lại trang, số lượng của giỏ hàng hiển thị là 0 trong khi đang có sản phẩm
c. Kết quả mong muốn: Khi tải lại trang, số lượng của giỏ hàng hiển thị đúng với số lượng sản phẩm trong giỏ hàng
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://caythuoc.vn/ và quan sát hiển thị số lượng của giỏ hàng hiện tại là 0 vì chưa có sản phẩm trong giỏ
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/8fe6ef29-e40a-4c3a-9c84-bc28c8857198">
ii. #1 Tiến hành thêm một vài sản phẩm vào giỏ hàng và hiện tại giỏ hàng vẫn hiển thị đúng số lượng sản phẩm
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/7c1ab4f1-2b15-4688-99fd-f6b10966ff46">
iii. #1 Tải lại trang và quan sát hiển thị số lượng giỏ hàng là 0 trong khi trong giỏ hàng đang có sản phẳm
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/9b0b25b8-8201-4d0f-aad0-cc976192b7eb">

**Comment by 31211027582** [comment]
Vấn đề không phải là lỗi GUI. Thay vào đó, đó là một lỗi trong quá trình quản lý dữ liệu ứng dụng. Sau khi người dùng mua sản phẩm và tải lại trang, dữ liệu giỏ hàng không được cập nhật đúng cách trong phiên làm việc, làm cho thông tin giỏ hàng bị mất và người dùng thấy giỏ hàng trống dù trong phần chi tiết vẫn còn. Vấn đề này ảnh hưởng đến chức năng mua hàng và quản lý giỏ hàng, không liên quan trực tiếp đến việc hiển thị trên giao diện người dùng.
