### ISSUE TITLE
[Nhóm#04] - Lỗi giao diện - Lỗi layout chi tiết sản phẩm không thẳng hàng- Trang https://caythuoc.vn 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#133]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Hiển thị mô tả sản phẩm bị không thẳng hàng với các layout khác
c. Kết quả mong muốn: Hiển thị mô tả sản phẩm được sắp xếp thẳng hàng với các layout khác
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/633abeba-1e2e-4a90-8ce1-ed553962b6db">
ii. #1 Truy cập vào 1 sản phẩm đang có chương trình giảm giá và quan sát các hiển thị mô tả
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/e074f600-2b72-442a-b322-d3137a1dbac6">

**Comment by 31211027582** [comment]
Phần này thực chất chia làm phần giá và phần thông tin, khi nào từng hàng lùi vào lộn xộn thì đây mới là lỗi, còn ở đây thì web lùi theo nhóm thông tin liên quan.
