### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Không có mã chống lại hình thức tấn công thông qua XSS - Trang https://gamevui.vn/

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#143]
a. Web browser: Chrome/ version: 114.0.0.0
b. Các bước phát hiện lỗi:
i. #1: Mở trình duyệt [https://gamevui.vn/](url)
ii. #2: Mở F12 để bật Dev Tool kiểm tra thanh tìm kiếm
iii. #3: Nhập từ khóa vào thanh tìm kiếm sau đó kiểm tra Dev Tool. Không tìm thấy mã thông báo Anti-CSRF nào
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/aa3ca8a3-6034-4057-b7a1-71feab02a784)

iv. #4: Kiểm tra lại lần nữa. Vào trang web [https://pagespeed.web.dev/](url). Nhập https://gamevui.vn/ vào mã url. Sau đó chọn Phân tích
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/2d7d2d04-8240-4c2d-bcaa-44aa46891c57)

v. #5: Lướt xuống phần TIN CẬY VÀ AN TOÀN:
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/44a1a42e-afd4-43af-adca-3fff97b1dc26)

c. Kết quả thực tế: Không tìm thấy mã thông báo Anti-CSRF nào(Thiếu 2 lệnh script-src , object-src)
d. Kết quả mong muốn: Có đẩy đủ 2 lệnh trên tránh trường hợp tấn công thông qua XSS.

**Comment by 31211027598** [comment]
@31211027599 Như thầy nói thì lỗi này là dùng công cụ tool để tìm ra lỗi phi chức năng, nên không được tính là lỗi. Lỗi này sẽ được chấp nhận nếu cá nhân tự tìm ra chính lỗi này mà không dùng công cụ tool hay phần mềm.
