### ISSUE TITLE
[NHÓM#07]- Lỗi Phi Chức Năng - Có nhiều document.write() làm load trang web chậm- trang https://gamevui.vn/

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#144]
a. Web browser: Chrome/ version: 114.0.0.0
b. Các bước phát hiện lỗi:
i. #1: Mở trình duyệt https://gamevui.vn/
ii. #2: Mở F12 để bật Dev Tool kiểm tra.
iii. #3: Sau đó Ctrl + F. Nhập từ khóa " document.write()" vào thanh tìm kiếm sau đó kiểm tra Dev Tool.
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/45f7946f-435b-4a59-a257-c2e478979540)

c. Kết quả thực tế: Có tận 8 dòng document.write(). Đối với những người dùng có kết nối chậm, các tập lệnh bên ngoài tự động được đưa vào qua document.write() có thể làm trang tải chậm hàng chục giây. (document.write() thường được dùng để đưa nhiều quảng cáo)
d. Kết quả mong muốn: Xóa tất cả document.write() trong web trên. Nếu nó đang được sử dụng để chèn các tập lệnh của bên thứ ba, thay vào đó hãy thử sử dụng tải không đồng bộ.

**Comment by 31211027598** [comment]
@31211027599 đây là trang dịch vụ giải trí nên tất yếu phải có những quảng cáo kèm theo. Tuy nhiên các quảng cáo này không mất nhiều thời gian để phản hồi về người dùng nên không được tính là lỗi phi chức năng.
