### ISSUE TITLE
[Nhóm#06] - Lỗi giao diện- Dấu chấm và dấu phẩy không đồng nhất - trang https://govirlunteer.ueh.edu.vn/

### ISSUE THREAD

**Issue by conghieu239** [UEHMonQAQC/23_902#151]
a. Web Browser: Google Chrome Version 116.0.5845.111
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang govirlunteer.ueh.edu.vn sau đó kéo xuống dưới mục "Hoạt động nổi bật nhất".
![image](https://github.com/UEHMonQAQC/23_902/assets/114810571/f6d14900-9d74-4f21-b91d-e3f0364ee885)
ii. #2: Chọn bài "ĐĂNG KÝ THAM GIA MẶT TRẬN TP. HỒ CHÍ MINH - CHIẾN DỊCH TÌNH NGUYỆN SINH VIÊN KINH TẾ 2022 - CHẶNG 1: MÙA HÈ XANH".
![image](https://github.com/UEHMonQAQC/23_902/assets/114810571/31bc4b35-7b0e-4d21-819b-9a7901bc718c)

iii. #3: Kéo xuống mục "Các nhiệm vụ tình nguyện viên sẽ tham gia".
![image](https://github.com/UEHMonQAQC/23_902/assets/114810571/ae0c2023-ace6-4160-8953-e88c1fd59088)

c. Kết quả thực tế: Dấu chấm và phẩy không thống nhất.
d. Kết quả mong đợi: Dấu chấm và dấu phẩy thống nhất.

**Comment by 31211027613** [comment]
này mình nghĩ không hẳn là lỗi á nhóm ơi
