### ISSUE TITLE
[Nhóm#09] - Lỗi phi chức năng - DDOS - trang mwc.com.vn 

### ISSUE THREAD

**Issue by Danny-98** [UEHMonQAQC/23_902#152]
Web Browser:
Safari
Các bước phát hiện lỗi:
Bước 1: Sử dụng Terminal chạy lệnh `ping mwc.com.vn` rồi chờ khoảng 1 giờ có thể dùng nhiều máy để nhanh hơn.

Bước 2: Mở Web Browser thực hiện truy cập trang web https://www.mvc.com.vn/

<img width="1430" alt="Screenshot 2023-09-01 at 19 36 37" src="https://github.com/UEHMonQAQC/23_902/assets/42095121/df9e19f7-71a3-4b59-b508-741baec09d58">

Kết quả thực tế
- Trang web bị nghẽn băng thông không thể tải và bị treo.

Kết quả mong đợi
- Trang web có thể truy cập bình thường.

**Comment by tquann286** [comment]
@Danny-98 thêm video dùng máy khác truy cập vào trang web cho thấy web bị sập giúp e

**Comment by tquann286** [comment]
Vẫn chưa thấy video
