### ISSUE TITLE
[Nhóm#04] - Lỗi chức năng - Thanh lọc Map ngưng hoạt động khi chọn Vinh Long Campus- Trang https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#158]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi chọn map Vinh Long Campus, thanh lọc map bị ngưng hoạt động
c. Kết quả mong muốn: Khi chọn map Vinh Long Campus, thanh lọc map hoạt động bình thường
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://smartlib.ueh.edu.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/eccf2e4e-55be-4c49-92a6-5f69b2672135">
ii. #1 Lướt xuống và chọn vào mục Maps
<img width="958" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/12a03c59-9f98-4094-894a-f64a54bc8994">
iii. #1 Ở mục lọc map, lựa chọn "VINH LONG Campus", tiến hành truy cập lại vào thanh lọc map sẽ không truy cập vào lại được
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/41b73f9c-401b-4335-9927-0e38533ca943">

**Comment by 31211027582** [comment]
Trùng lỗi #157

**Comment by 31211027596** [comment]
Ủa tui thấy mặc dù bị lỗi giống nhau nhưng cách truy cập lỗi khác nhau nên tui chia thành hai cái, sao không được á :(
