### ISSUE TITLE
[Nhóm#05] - Lỗi phi chức năng - Không sử dụng HTTPS encryption để mã hóa dữ liệu - Trang http://www.baolamdong.vn/

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#159]
a. Web Browser: Chrome Version 116.0.5845.141
b.Kết quả thực tế: không có hệ thống bảo vệ trang web để  mã hóa  dữ liệu khiến bên thứ ba dễ dàng đọc và xâm nhập các gói dữ liệu gốc.
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/2d4317e1-e28c-49b7-8aae-48472932e74d)
c. Kết quả mong muốn: sử dụng HTTPS, SSL hoặc TLS sẽ được sử dụng để mã hóa thông tin được gửi đến và đi từ máy chủ
d. Các bước phát hiện lỗi:
i. Mở trình duyệt Chrome.
ii. Truy cập trang web baolamdong.vn
iii. Click vào ellipsis ở bên phải trên cùng của trình duyệt 
iv. Sau đó vào: More tools > Developer tools > Security
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/029220be-31d4-4a85-99f2-9fca09d09302)

**Comment by 31211027582** [comment]
Bạn ơi trình bày nhất quán nội dung giúp mình với, ở trên là Microsoft Edge, còn ở dưới bạn nói là vào Chrome.

**Comment by 33221025087** [comment]
> Bạn ơi trình bày nhất quán nội dung giúp mình với, ở trên là Microsoft Edge, còn ở dưới bạn nói là vào Chrome.

mình đã edit lại

**Comment by 31211027582** [comment]
Theo như thầy nói trên lớp thì lỗi này không phải lỗi phi chức năng do wed này không dùng https
