### ISSUE TITLE
[Nhóm#05] - Lỗi giao diện - Lỗi bố cục , khoảng trống nhiều http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#16]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: bố cục không đồng nhất, khoảng trống nhiều
c. Kết quả mong muốn: Sắp xếp bố cục đồng nhất , căn chỉnh theo dòng để người đọc dễ tìm kiếm và sử dụng 
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào chọn vào mục “ Multimedia”
 
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/95de7bc6-965c-499f-a819-79362d392893)

**Comment by 31211027582** [comment]
khi tui chọn vào mục “ Multimedia” thì chỉ xuất hiện như này                                                                                                            
![image](https://github.com/UEHMonQAQC/23_902/assets/142146180/74c897e2-2b5a-46e8-8173-b3958e1a5ede)
mọi người xem rồi hướng dẫn chi tiết hơn giúp mình

**Comment by 31211027582** [comment]
Đây là phần dropdown cho toàn bộ phần navbar khi bấm vào dấu 3 chấm, tức là ta sẽ có cái nhìn tổng quan hơn có tất cả bao nhiêu mục chính và các mục con bên trong, phần này tác biệt so với phần nav ở trên. Nên ta thấy mục Pháp luật, Tòa soạn - Bạn đọc, ... xuống 1 hàng khác,  tức là đây là phần bố cục cho phần dropdown.
