### ISSUE TITLE
[Nhóm#06] - Lỗi phi chức năng - Không có mã chống lại hình thức tấn công thông qua XSS - Trang https://yame.vn/

### ISSUE THREAD

**Issue by son1258** [UEHMonQAQC/23_902#161]
a. Web browser: Microsoft Edge /Version 116.0.1938.69
b. Các bước phát hiện lỗi:
i.#1 : Mở trình duyệt: https://yame.vn/ và chọn biểu tượng tìm kiếm 
![image](https://github.com/UEHMonQAQC/23_902/assets/134360548/fac009a6-17ea-42c6-8e7a-5ad0ab906e34)
ii.#2: Ấn F12 để mở dev tool kiểm tra thanh tìm kiếm. Nhập từ khóa vào thanh tìm kiếm sau đó kiểm tra dev tool. Không tìm thấy mã thông báo Anti-CSRF nào
![image](https://github.com/UEHMonQAQC/23_902/assets/134360548/36c17828-390f-4d61-b0f9-47407c383e7e)
iii.#3 Kiểm tra lại bằng cách truy cập trang web: https://pagespeed.web.dev/. Rồi thả URL:  https://yame.vn/ vào và chọn phân tích
![image](https://github.com/UEHMonQAQC/23_902/assets/134360548/ed2c2659-1fa1-4b89-9b0e-178f30323c45)
iv: #4: Kéo xuống phần Trust and Safety
![image](https://github.com/UEHMonQAQC/23_902/assets/134360548/5e002096-2227-4f2e-aa57-30199f60b623)
c. Kết quả nhận được: Không tìm thất bất cứ mã thông báo Anti-CSRF nào (script-src, object-src )
d. Kết quả mong muốn: Có đẩy đủ 2 lệnh trên tránh trường hợp tấn công thông qua XSS.

**Comment by 31211027613** [comment]
@son1258 dạ theo như ý thầy, thì lỗi này cần thêm minh chứng (thực tế hóa lỗi ngoài tools test, tận dụng lỗi đó) để xác thực, anh và các bạn xem xét sửa lại giúp em nha.
