### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - No redirect or canonical to HTTPS homepage from HTTP version - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027606** [UEHMonQAQC/23_902#177]
a. Web Browser: Microsoft Edge Version 117.0.2045.7 - Hệ điều hành MacOS Sonoma 14.0 
b. Các bước phát hiện lỗi: 
i.  1: Truy cập https://www.semrush.com/projects/
ii. 2: Sau đó chọn create project và nhập https://shop.ueh.edu.vn/
iii. 3: xuất hiện lỗi: 
<img width="1205" alt="Screenshot 2023-09-05 at 15 21 40" src="https://github.com/UEHMonQAQC/23_902/assets/143168645/fec37960-a288-422a-a252-3a0a127cd0b2">

c: Xuất hiện 2 đường dẫn http và https:
<img width="672" alt="Screenshot 2023-09-05 at 15 21 58" src="https://github.com/UEHMonQAQC/23_902/assets/143168645/9555e797-6518-4ada-9d0c-aafa74f5cdb5">

d. Kết quả mong muốn: Thực hiện một trong những thao tác sau:
- Chuyển hướng trang HTTP của bạn sang phiên bản HTTPS thông qua chuyển hướng 301
- Đánh dấu phiên bản HTTPS của bạn là phiên bản ưa thích bằng cách thêm rel="canonical" vào các trang HTTP của bạn

**Comment by 31211027613** [comment]
Mình đang không hiểu ý của lỗi này là gì ấy. Bạn có thể giải thích rõ hơn về lỗi này giúp mình nhé

**Comment by 31211027606** [comment]
Theo như mình tìm hiểu thì lỗi sẽ như thế này:

“No redirect or canonical to HTTPS homepage from HTTP version” là thông báo lỗi có thể xuất hiện khi kiểm tra một trang web.Điều đó có nghĩa là trang web không tự động chuyển hướng người dùng từ phiên bản HTTP của trang chủ sang phiên bản HTTPS và không có thành phần liên kết chuẩn nào trong phiên bản HTTP trỏ đến phiên bản HTTPS là phiên bản ưa thích của trang.

Phần tử liên kết chuẩn là phần tử HTML giúp quản trị viên web ngăn chặn các vấn đề trùng lặp nội dung bằng cách chỉ định phiên bản “chuẩn” hoặc “ưa thích” của trang web. Nó được biểu thị bằng mã định danh rel=canonical và nằm trong tiêu đề 2 của tài liệu: https://sitechecker.pro/site-audit-issues/canonical-from-http-to-https/.

Để khắc phục sự cố này, bạn có thể cập nhật tệp .htaccess của trang web của mình để bao gồm các quy tắc chuyển hướng người dùng từ phiên bản HTTP của trang chủ sang phiên bản HTTPS. Bạn cũng có thể thêm phần tử liên kết chuẩn vào phiên bản HTTP của trang chủ trỏ đến phiên bản HTTPS là phiên bản ưu tiên. Điều quan trọng là phải khắc phục sự cố này vì nó có thể ảnh hưởng đến hiệu suất SEO, tính bảo mật và niềm tin của người dùng trên trang web của bạn.

**Comment by 31211027613** [comment]
mình cảm ơn bạn nhiều

**Comment by 31211027613** [comment]
@31211027606 theo như ý thầy, thì lỗi này cần thêm minh chứng (thực tế hóa lỗi ngoài tools test, tận dụng lỗi đó) để xác thực, các bạn xem xét sửa lại giúp mình

**Comment by 31211027606** [comment]
Khi thực hiện đoạn code 
[Test-Redirect-Canonical.py.zip](https://github.com/UEHMonQAQC/23_902/files/12643305/Test-Redirect-Canonical.py.zip) thì kết quả xuất hiện: 
<img width="351" alt="Screenshot 2023-09-17 at 23 28 57" src="https://github.com/UEHMonQAQC/23_902/assets/143168645/3ae1d159-24aa-460f-8fa3-d135b95ae380">

Ở đây mình sử dụng web paypal để so sánh, cho thấy kết quả như hình trên.
Tại trang http://shop.ueh.edu.vn không có điều hướng từ http đến https và canonical ở đây cũng không có. Nhưng khi chỉ nhập "http" thì trang web sẽ tự chuyển hướng từ http sang https và HTML của trang web chứa liên kết canonical có URL "https", cho biết rằng đây là phiên bản chuẩn của trang. Các liên kết canonical phục vụ một mục đích cụ thể trong việc quản lý nội dung trùng lặp và chỉ định các URL ưa thích cho mục đích SEO. Tuy nhiên, chúng không thay thế được lợi ích bảo mật và quyền riêng tư của HTTPS. Đối với các trang web xử lý dữ liệu nhạy cảm, ưu tiên sự tin cậy của người dùng và muốn đảm bảo bảo mật dữ liệu, chúng tôi đặc biệt khuyến khích triển khai HTTPS bằng chuyển hướng HTTP sang HTTPS. Liên kết Canonical có thể được sử dụng kết hợp với HTTPS để giải quyết các nhu cầu quản lý nội dung và SEO. Vấn đề ở đây là trang web không sử dụng chuyển hướng http đến https, có thể điều đó trang web có sẵn các cấu hình hoặc quy tắc phía máy chủ để thực thi HTTPS. 

So sánh với web paypal thì ở đây đã được cấu hình bảo mật ở cả 2 đường dẫn "http" và "https"

Kết quả mong đợi: Có thể cấu hình bảo mật ở cả 2 đường dẫn để tránh các rủi ro làm lộ thông tin khách hàng,...
