### ISSUE TITLE
[Nhóm#05] - Lỗi giao diện - Lỗi hiển thị - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#18]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: Lỗi hiện thị đoạn [links(right)] code html hoặc css
c. Kết quả mong muốn: không bị lỗi hiển thị 
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang báo [Đà Lạt năm 1908 (tiếp theo và hết) - Báo Lâm Đồng điện tử (baolamdong.vn)](http://baolamdong.vn/dalatxuanay/201403/da-lat-nam-1908-tiep-theo-va-het-2448661/)

![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/b33c8846-13f8-4b6d-890b-ad6391eebaaf)

**Comment by 31211027582** [comment]
Đây chính là nội dung bên trong thẻ html (div) chứ không phải lỗi hiển thị đoạn [links(right)] code html. Vì vậy, không liên quan trực tiếp đến lỗi GUI, mà thường là một sai sót trong việc soạn thảo và đăng nội dung.
![Screenshot 2023-08-27 214941](https://github.com/UEHMonQAQC/23_902/assets/142146180/a5fb3b25-f824-4f07-be01-f31797c0dbe0)
