### ISSUE TITLE
[Nhóm#05] - Lỗi giao diện - Lỗi in đậm văn bản http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#19]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: không đồng bộ in đậm và chữ thường trong bài báo
c. Kết quả mong muốn: không bị lỗi hiển thị
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang báo [Đà Lạt năm 1908 (tiếp theo và hết) - Báo Lâm Đồng điện tử (baolamdong.vn)](http://baolamdong.vn/dalatxuanay/201403/da-lat-nam-1908-tiep-theo-va-het-2448661/)
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/972d676c-f1c8-4415-b36b-57a1e04f27f5)

**Comment by 31211027582** [comment]
Đây là một vấn đề liên quan đến thiết kế và định dạng nội dung, không phải là việc hiển thị không đúng cách trên giao diện người dùng. Khi chữ được in đậm, mục đích thường là làm nổi bật hoặc làm rõ nội dung quan trọng hơn, không phải để tạo ra lỗi GUI.
