### ISSUE TITLE
[Nhóm#07] - Lỗi phi chức năng - Lỗi XSS - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027625** [UEHMonQAQC/23_902#196]
a. Web Browser: Google Chrome 116.0.5845.111 ( Bản chính thức)(64bit) Laptop: Dell Vostro 15 3510 Win 11
b. Các bước để phát hiện lỗi:
i.#1: Chọn trình duyệt và đăng nhập vào https://khdtkt.ueh.edu.vn/
ii.#2: Điền đoạn mã dưới đây vào thanh tìm kiếm 
<script>alert('XSS attack')</script>
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/aa9b9ebb-2ea5-496f-94da-d7e466fc3d51)
iii.#3: Kết quả tìm kiếm: 
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/8079024d-1d3c-4566-9d7e-0f4f0bc25407)
c. Kết quả thực tế: Trang vẫn thực hiện chức năng tìm kiếm bình thường ( chỉ là không có tài liệu có nội dung trên )
d. Kết quả mong đợi: Trang web hiển thị cảnh báo lỗi hoặc khóa quyền truy cập tạm thời

**Comment by 31211027598** [comment]
@31211027573 
Đây không phải là lỗi phi chức năng nha bạn. Đây chỉ là do hệ thống hiện ra nội dung tìm kiếm mà bạn nhập.
Khi xảy ra lỗi XSS attack thì sẽ hiển thị 1 popup ngay trên web.

![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/21e2197b-c0a5-49ee-9834-55023985c5cb)
