### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Không truy vấn được dữ liệu - Trang https://khdtkt.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#199]
a. Bug: Lỗi không truy vấn được dữ liệu
b. Trình duyệt: Google Chrome
c. Các bước phát hiện lỗi:
    #1. truy cập trang Web
    #2. Trên thanh menu chọn Kế hoạch đào tạo -TKB - Lịch thi- Giảng đường
    #3. chọn Tra cứu Kế hoạch đào tạo
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/325d61ca-a784-48a1-81c3-c522480f5a3a)

    #4 Cuộn xuống và chọn trang thứ 3 (hoặc 4)
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/dcc36c6d-6107-414f-8efc-542c904b9238)

    #5 Từ trang 3 (hoặc 4) cuộn lên để tìm tên môn học Quản trị kênh phân phối trong du lịch
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/8b322e6b-e402-4af5-9913-248bcba23e33)
    #6 Cuộn lên thanh công cụ tìm kiếm, ở mục chọn học phần điền vào tên môn đó
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/a18db526-344f-4224-ad46-f0ec43bf5bd4)
    #7 Kiểm tra và kết quả là không tìm thấy
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/54b1e558-a200-4eae-b0b0-bdcf1d46bc4e)

d. Kết quả thực tế: ở tổng kết quả tìm kiếm được thì báo là 3 trên tổng số 3 học phần, nhưng lại không tìm thấy học phần nào
e. Kết quả mong đợi: Phải hiển thị ra được 3 học phần đó, hoặc nếu không có thì từ bước thư 5 đã không thấy học phần và khi tìm kiếm sẽ hiển thị thông báo không tìm thấy như hình bên dưới chứ không có hiển thị như trên kết quả thực tế
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/3677865c-9481-481e-a3f3-d451ba2b30c8)

**Comment by 31211027598** [comment]
@31211027573 
Máy mình vẫn tìm được 3 học phần đó nha.

![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/810f10de-a58a-432a-a5f6-c0a748392f04)

![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/e9b6a1ae-e9a1-40e3-b24d-0de1ad6ed38d)
