### ISSUE TITLE
[Nhóm#09] - Lỗi Phi chức năng - Thời gian load trang chậm - Trang https://ueh.edu.vn

### ISSUE THREAD

**Issue by newbiecode123456** [UEHMonQAQC/23_902#202]
**Web Browser**
Google Chrome
**Các bước phát hiện lỗi**
1.	Đổi sang chế độ Low-end mobile
2.	Truy cập trang (reload)
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/08fbec52-b871-4023-99d8-c22f15ba744c)

3.	Quan sát thấy sau 5s site chưa load xong
4.	Tổng thời gian load site (cho các thiết bị đời cũ) là khoảng 30s => chậm
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/35beb546-b932-41da-b8b0-364b1c5df4aa)

**Kết quả mong muốn**
Tốc độ load site không quá chậm đối với thiết bị đời cũ
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/ba305f3b-656f-4ff9-b8b0-897d311e31a9)

**Kết quả thực tế**
Thời gian load site khá lâu (30s)

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/09cb7e20-8683-47da-85a8-4e95dca04efe)
- Không chấp nhận, chỉnh sang chế độ Low-end (Slow 3G) thì việc load chậm là tất yếu, 
- Chưa kể đây là chức năng dành cho developer test trang web, thì việc một user bình thường vào chỉnh mấy này làm gì

**Comment by tquann286** [comment]
Trang web chưa đủ lớn để có thể hỗ trợ các thiết bị yếu
