### ISSUE TITLE
[Nhóm#09] - Lỗi phi chức năng - Lỗi XSS - Trang https://ueh.edu.vn

### ISSUE THREAD

**Issue by newbiecode123456** [UEHMonQAQC/23_902#204]
Web Browser
Google Chrome
Các bước phát hiện lỗi
1.	Truy cập ueh.edu.vn
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/2e348260-704a-460d-8190-350963a1d933)

2.	Dán đoạn: &quot;%20onfocus=&quot;alert(document.cookie)
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/4eeb60dd-d985-48fe-a803-8f58442bc029)

3.	Sau khi nhấn tìm dùng dev tool kiểm tra
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/cb69e31c-5920-4443-80c2-c04c372cd4db)

4.	Khi so với từ khoá hợp lệ thì input sai syntax ở value => document.cookie được thực thi
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/d84f7481-e9a8-4553-b569-b674564b7304)

Kết quả mong muốn
Các đoạn script không bị tiêm được vào các input
Kết quả thực tế
Có thể tiêm script vào

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/de2b310e-edb9-4696-9371-b3f476e41c84)
E thực hiện theo và chả thấy gì bất thường cả, trường hợp này sẽ được tính lỗi nếu như trình duyệt popup lên thông báo (alert) cho thấy dữ liệu của cookie thì sẽ được chấp nhận

**Comment by tquann286** [comment]
Đã tham khảo thầy và  kết luận không phải lỗi
