### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Lỗi SQL Injection - Trang https://gamevui.vn/

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#212]
a. Web browser: Chrome/ version: 114.0.0.0
b. Các bước phát hiện lỗi:
i. #1: Mở trình duyệt https://gamevui.vn/
ii. #2: Chọn vào thanh tìm kiếm ghi đoạn mã SQL: 
SELECT * FROM game WHERE game_id = $_GET[game_id]

![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/a063e15b-ce1f-4861-ad76-968265b7324d)

c. Kết quả thực tế: Vẫn có thể tìm kiếm được và ra được như trò trên bên dưới
d. Kết quả mong muốn: Ngăn cản người dùng nhập mã SQL vào.

**Comment by 31211027598** [comment]
@31211027599 
- Vì đây là một web game, nên mỗi kí tự nhập ở ô tìm kiếm không cần phải chính xác. Có thể nhập gần đúng là tìm được game.
- Như đoạn mã SQL trên SELECT * FROM game WHERE game_id = $_GET[game_id]
- Có thể thấy trong đoạn mã này chứa chữ "game".
- Nên các trò chơi tìm được đều có chữ game .
- Nên đây không phải là lỗi phi chức năng.
