### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Lỗi SQL Injection - Trang https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027574** [UEHMonQAQC/23_902#215]
a. Trình duyệt web: Google Chrome phiên bản 116.0.5845.111 - Hệ điều hành: Windows 11
b. Các bước phát hiện lỗi:
i. #1 Truy cập trang web caythuoc.vn
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/e4f5e8f0-9335-479c-9d98-2c7987ab8b54)
ii. #2 Điền đoạn mã ở dưới đây vào thanh tìm kiếm:
SELECT * FROM thuoc WHERE thuoc_id = $_GET[thuoc_id]
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/19b590e4-833e-485c-acab-40deb24cd19b)
iii. #3 Màn hình vẫn hiển thị ra kết quả:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/df9116df-c40f-4c86-9d7b-380e24015568)
c. Kết quả thực tế: Vẫn có thể tìm kiếm được các sản phầm thuốc (mặc dù đây là đoạn mã SQL của cơ sở dữ liệu, không phải tên sản phẩm thuốc)
d. Kết quả mong muốn: Ngăn cản người dùng nhập mã SQL để tìm kiếm, người dùng chỉ có thể tìm kiếm bằng tên sản phẩm thuốc

**Comment by 31211027582** [comment]
Khi nhập đoạn query  SELECT * FROM thuoc WHERE thuoc_id = $_GET[thuoc_id] vào thanh tìm kiếm, đây là một tìm kiếm thông qua từ khóa 'thuoc' trong câu truy vấn, không liên quan đến lỗi pcn.  Ngoài ra, không có vấn đề về việc mất mát thông tin hoặc nguy cơ bảo mật.
