### ISSUE TITLE
[Nhóm#07] - Lỗi phi chức năng - Người khác có thể dò tim password - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027623** [UEHMonQAQC/23_902#218]
a. Web Browser: Google Chrome 113.0.5672.93 (Phiên bản Chính thức) (64 bit)
b. Các bước để phát hiện lỗi:
i.#1: Mở trình duyệt https://khdtkt.ueh.edu.vn/
ii.#2: Vào Đăng nhập ở góc phải trên cùng.
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/4359ddbd-1447-475b-b936-41ad08ed6c0a)
iii.#3: Nhập tài khoản đã được tạo từ trước vào ô tài khoản đăng nhập ( tk: [tuannm@ueh.edu.vn](mailto:tuannm@ueh.edu.vn) với tài khoản trên là của giảng viên Nguyễn Mạnh Tuấn). Nhập mậu khẩu không chính xác nhiều lần.
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/1899fe07-4256-460f-89e3-da3616a2821b)
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/48904349-449f-4484-97f4-033b52b0589d)
c. Kết quả thực tế : Mật khẩu không đúng nhiều lần mà không bị cảnh báo hoặc khoá tài khoản.
d. Kết quả mong muốn : Khi nhập sai quá nhiều hệ thống sẽ hiển thị "bạn có muốn lấy lại tài khoản" hoặc thông báo về số lần nhập sai sẽ bị khoá tài khoản hoặc hệ thống được cài đặt Captcha hợp lý để hạn chế việc spam những request nhạy cảm khả dĩ có thể làm hỏng hệ thống (đăng ký tài khoản, đăng nhập…) để tăng tính bảo mật .

**Comment by 31211027598** [comment]
@31211027623 
Thầy nói rằng đây là chức năng của người phát triển, không phải lỗi phi chức năng về bảo mật.
