### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Hiển thị web blocked khi click xem chi tiết số điện thoại - Trang https://caythuoc.vn/ 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#220]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi lựa chọn xem chi tiết về thông tin số điện thoại trong chi tiết sản phẩm, web chuyển hướng đến một trang web blocked
c. Kết quả mong muốn: Khi lựa chọn xem chi tiết về thông tin số điện thoại trong chi tiết sản phẩm, web chuyển hướng đến một trang web về liên hệ hoặc không cho phép click.
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/fbdbdd95-709c-4b1d-973e-b766ada1f485">
ii. #1 Tìm kiếm sản phẩm "BÌNH NGÂM RƯỢU HÀN QUỐC 5 LÍT"
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/cb499fd3-477c-4422-9f05-5d56a58802b2">
iii. #1 Xem sản phẩm và lướt xuống mục liên hệ click vào số điện thoại hotline
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/6b65cae9-66a6-4ea3-8843-ba84c4c7182e">
iii. #1 Quan sát trang web mới được hiển thị 
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/4d2ee337-e012-40ba-b488-5ac52171fa6c">

**Comment by 31211027582** [comment]
Lỗi phi chức năng liên quan đến bảo mật thường liên quan đến việc lợi dụng các lỗ hổng bảo mật hoặc vi phạm các nguyên tắc bảo mật để truy cập hoặc thu thập thông tin không được phép từ một trang web. Trong trường hợp này, việc chuyển đến trang "about:blank#blocked" không phải là một lỗi phi chức năng, mà là một tính năng bảo mật hoặc chặn của trình duyệt hoặc hệ thống, nhằm bảo vệ người dùng khỏi các hoạt động không mong muốn hoặc tiềm ẩn nguy cơ bảo mật.

**Comment by 31211027596** [comment]
Ò tui hiểu rồi, cảm ơn pà
