### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Thiếu thẻ thuộc tính Viewport ở <head> trong html - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025087** [UEHMonQAQC/23_902#221]
a.Web Browser: Chrome Version 116.0.5845.141
b.Kết quả thực tế: Thiếu thẻ meta Viewport ở <head> trong html
c. Kết quả mong muốn: Sử dụng Thẻ meta viewport cho phép bạn kiểm soát việc thu nhỏ và phóng to nội dung trên màn hình của người dùng, đảm bảo rằng trang web của bạn hiển thị đúng cách trên các thiết bị có kích thước màn hình khác nhau.
d. Các bước phát hiện lỗi:
i. Mở trình duyệt Chrome.
ii. Truy cập trang web baolamdong.vn
iii. Click vào ellipsis ở bên phải trên cùng của trình duyệt
iv. Sau đó vào: More tools > Developer tools > issue 
v. Sẽ thấy tool báo lỗi thiếu thuộc tính viewport
 
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/b0aa2e6a-be2a-46a3-9ff4-8265aa0bbabc)

vi. Vào Elements cũng trong thanh công cụ của Developer tools 
 
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/a07d553f-5bb1-4402-bdf2-54bbb9cd2201)

vii. Kiểm tra không thấy thuộc tính viewport ( thuộc tính viewport tương tự hình ảnh ví dụ bên dưới)
 
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/4c3944ca-b541-49af-9e33-19bfbf360478)

 Ví dụ: thuộc tính viewport có trong <head> ở web shop của UEH 
![image](https://github.com/UEHMonQAQC/23_902/assets/143169704/3548093c-0aa1-4924-b671-6184c9686dea)

**Comment by 31211027582** [comment]
Theo như tui tìm thì thẻ meta trang báo lâm đồng vẫn có thuộc tính viewport nhe, với lại hôm trước nhóm tui có hỏi thầy thì lỗi thiếu thuộc tính ở thể meta thường thì không phải lỗi chức năng, vì nó không ảnh hưởng đến chức năng chính của trang web
![image](https://github.com/UEHMonQAQC/23_902/assets/142146180/a18c447a-f441-426a-b404-a668b27b1d5b)
