### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi link liên kết - trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#224]
a. Web Browser: Goodle Chrome Version 116.
b.Kết quả thực tế: website liên kết không hoạt động
c. Kết quả mong muốn: Chuyển qua website liên kết
d. Các bước phát hiện lỗi:
i.#1 Truy cập trang http://www.cpv.ueh.edu.vn/ , vào phần liên kết website chọn vào mục “[Tổng Liên đoàn lao động Việt Nam] ”
<img width="701" alt="Screenshot 2023-09-14 090030" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/e4f6033e-a9d2-4f31-90ce-48fab7dc191c">
<img width="323" alt="Screenshot 2023-09-14 090604" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/012db3d0-38c9-4825-9801-06da5e0af143">
ii.#2 Trang [Tổng Liên đoàn lao động Việt Nam] không truy cập được do lỗi typo
<img width="776" alt="Screenshot 2023-09-14 090819" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/dbfb44fb-056c-484b-9197-c770dacd543c">

**Comment by 31211027582** [comment]
Lỗi này cùng 1 kiểu lỗi với lỗi  #222 nhe.
