### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Hệ thống tiếp nhận đoạn mã code thông báo - trang https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#234]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Thanh tìm kiếm tiếp nhận mã code và Thực thi được đoạn script thông báo “1111”
c. Kết quả mong muốn: Hệ thống không tiếp nhận đoạn mã.
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/fbdbdd95-709c-4b1d-973e-b766ada1f485">
ii. #1 Nhập vào thanh tìm kiếm mã code "<script>alert("1") </script>"
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/5cdc25fa-204a-47be-9bee-7a50750818f3">
iii. #1 Xem kết quả hiển thị 
<img width="384" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/be4d4551-a287-47d2-bc17-d50ec760d71c">

**Comment by 31211027582** [comment]
Trùng lỗi #69
