### ISSUE TITLE
[Nhóm#01] – Lỗi Phi Chức Năng – Trang web không thể truy cập - Trang https://daklak24h.com.vn

### ISSUE THREAD

**Issue by QuanTrinhUEH** [UEHMonQAQC/23_902#248]
a. Web Browser: Cốc Cốc phiên bản 121.0.188
b. Các bước để phát hiện lỗi:
i. #1: Chọn trình duyệt và vào trang web https://daklak24h.com.vn
ii.#2: Kéo xuống cuối trang và chọn vào biểu tượng g+ phát hiện lỗi
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/9b5b2c1c-7dd0-48b3-9017-60b779dea599)
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/652efdfa-5df5-4d23-b736-372b998912dd)
c. Kết quả thực tế: Trang mạng xã hội Google+ của trang Đắk Lắk 24h không hoạt động.
d. Kết quả mong đợi: Người dùng được đưa đến trang mạng xã hội Google+ của trang Đắk Lắk 24h

**Comment by tquann286** [comment]
Đọc lại khái niệm lỗi phi chức năng nha bạn
