### ISSUE TITLE
[Nhóm#04] - Lỗi Phi chức năng - Lỗi 403 khi click vào UEH Student, Staff, ISB, ISB Westernsysney vào trang web - Trang smartlib.ueh.edu.vn

### ISSUE THREAD

**Issue by 31211027574** [UEHMonQAQC/23_902#252]
a. Trình duyệt web: Google Chrome phiên bản 116.0.5845.111 - Laptop: MSI Bravo 15 B5DD - Hệ điều hành: Windows 11
b. Kết quả thực tế: Xuất hiện lỗi 403: Error: app_not_configured_for_user, không thể truy cập được vào trang web khii click vào
c. Kết quả mong muốn: Mở ra giao diện đăng nhập
d. Các bước phát hiện lỗi:
i. #1 Truy cập web smartlib.ueh.edu.vn:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/2ca0697e-3faf-4220-b35c-a47f907970d8)
ii. #2 Đăng nhập vào web (Có hình mũi tên chỉa vào cái cửa):
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/64365ca0-7daa-49fd-a0a7-7124c655f675)
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/ba0d168f-ded1-4a80-a74f-0968d7f21888)
iii. #3 Khi nhấn vào UEH Student thì thấy xuất hiện lỗi này:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/f382ee8d-dcde-45cd-b4e9-43474832179d)
Khi click vào OpenAthens:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/8f1ef870-9f84-4306-acfa-9c847d9e3756)
Nếu như đăng nhập vào giao diện được thì đăng xuất tài khoản ra ngoài và xóa bộ nhớ đệm trên web:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/01b88f48-dc99-4de1-a446-6048a02c4583)
Rồi làm lại từ bước 1.

**Comment by tquann286** [comment]
Đọc lại khái niệm lỗi phi chức năng nha bạn

**Comment by 31211027582** [comment]
Tui vẫn chọn được nhe
https://drive.google.com/file/d/1uoLS_mzpv75q5vTJhXkoXFKeefRNXK_z/view?usp=sharing
