### ISSUE TITLE
[Nhóm#01] Lỗi phi chức năng – Lỗi XSS - https://alumni.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31211027571** [UEHMonQAQC/23_902#256]
A.	Web browser: Google chrome 
B.	Các bước phát hiện lỗi:
i.	Truy cập vào trang https://alumni.ueh.edu.vn/ và đăng nhập bằng tài khoản google
ii.	Sau khi đăng nhập nhấn vào phần Thiết lập.
![image](https://github.com/UEHMonQAQC/23_902/assets/142187446/c86d63af-c800-4dca-b2cb-2beafa85ce4c)

iii.	Click vào ô Họ hoặc Tên

![image](https://github.com/UEHMonQAQC/23_902/assets/142187446/651ff377-738f-400d-9f37-803bc4b74611)

iv.	Nhập đoạn mã <script>alert('Attack’)</script> và bấm nút Xác nhận
C.	Kết quả thực tế: Có lỗi XSS xảy ra.

![image](https://github.com/UEHMonQAQC/23_902/assets/142187446/512254e1-7d3b-4959-8372-e99f83de3da3)

D.	Kết quả mong đợi: Không có lỗi XSS và nội dung vẫn được giữ nguyên.

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/e8ca1e16-8b92-4809-8d6e-98d746098600)
Đã thực hiện theo nhưng không thấy popup thông báo Attack

**Comment by 31211027571** [comment]
Mình ghi sai trình duyệt sử dụng nó là Google Chrome ấy bạn check lại giùm mình

**Comment by 31211027571** [comment]
Tui viết nhầm phần trình duyệt ấy nó là Google Chrome
Với cả có ghi là chọn 1 trong 2 ô Họ Hoặc ô tên chứ không dùng cả 2 á

Vào 9:28, Th 6, 22 thg 9, 2023 Trung Quân ***@***.***> đã
viết:
