### ISSUE TITLE
[Nhóm#04] - Lỗi Phi chức năng - Cho phép người dùng có thể truy cập và tải về tài liệu mà không cần đăng nhập - Trang smartlib.ueh.edu.vn

### ISSUE THREAD

**Issue by ultimaten1** [UEHMonQAQC/23_902#259]
a. Trình duyệt web: Google Chrome phiên bản 116.0.5845.111 - Laptop: MSI Bravo 15 B5DD - Hệ điều hành: Windows 11
b. Kết quả thực tế: Cho phép người dùng truy cập được và tải về tài liệu
c. Kết quả mong muốn: Chặn người dùng truy cập đến tài liệu (chỉ có tài khoản trường cấp mới có thể truy cập được)
d. Các bước thực hiện:
i. #1 Truy cập web smartlib.ueh.edu.vn:
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/f14363d8-d8aa-4118-8430-edd66c753bb5)
ii. #2 Nhập từ khóa bất kì trên thanh tìm kiếm (ở đây mình dùng "documentation"):
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/90c06286-1ec6-433d-a25e-e15aa0df7c9e)
iii. #3 Click vào tài liệu có mục "PDF Full Text" (ở đây mình click vào tài liệu đầu tiên):
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/9a97740b-647c-4def-a331-c5294a1214be)
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/82c7b404-f04e-408e-8636-c24cf30ed766)
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/45cec24f-f637-44ad-b51e-06e9ac68d0b5)
iiii. #4 Thực hiện nhấn phím F12 và làm theo chỉ dẫn theo các hình dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/2f0c1401-1e9c-481f-8068-296f017ed3b4)
![Screenshot (442)](https://github.com/UEHMonQAQC/23_902/assets/86090698/931cf798-0629-436e-9920-aa291e31dabd)
![Screenshot (443)](https://github.com/UEHMonQAQC/23_902/assets/86090698/f0c24534-d3b8-4e07-aa3d-f3fce7147015)
iiiii. #5 Sau khi đã click vào link thì nó cho ra giao diện như hình dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/e5aea20d-9cac-46dc-8017-519371280714)
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/5229446f-8e26-4043-b4c8-79d9da48a2a2)

* Bình thường khi click vào "PDF Full Text":
![image](https://github.com/UEHMonQAQC/23_902/assets/86090698/463958b7-9043-490c-a2f6-57e063069c6b)

**Comment by 31211027582** [comment]
Tui vào web vẫn yêu cầu đăng nhập                                                                                                                                                          https://drive.google.com/file/d/17kN27OlT4kqi1SwYD7j2QNxsC11hAUQ0/view?usp=sharing
