### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Thanh lọc tìm kiếm điều kiện nhưng không lọc kết quả - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#26]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
b.Kết quả thực tế: kết quả trả không chính xác
c. Kết quả mong muốn: thanh lọc trả về đúng chi tiết
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào Chọn biểu tượng tìm kiếm

<img width="177" alt="Screenshot 2023-08-27 164842" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/a458fcc7-dfc7-4975-800a-f6641d43581c">

ii.#2 Nhập thông tin từ khóa bất kỳ cần tìm kiếm vào , ví dụ “77“ xuất ra 5 kết quả cho tất cả các mục

<img width="561" alt="Screenshot 2023-08-27 164948" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/8730796a-a80c-47a3-ad07-5b7a74cec222">

iii. #3 Khi chuyển qua chế độ lọc “tìm kiếm trong tiêu đề”, “tìm kiếm trong trích dẫn” thì kết quả vẫn trả về y như vậy, dù trong tiêu đề hay trích dẫn (nếu có) của kết quả tìm thấy không có từ khóa “77”

<img width="560" alt="Screenshot 2023-08-27 165158" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/edae5f02-e0e3-4433-b049-3237a8817ebf">

<img width="562" alt="Screenshot 2023-08-27 165310" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/07ec6ac3-5c00-4252-8eeb-8a86e3506c20">

**Comment by 31211027582** [comment]
Trùng lỗi #6
