### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Lỗi XSS - Trang smartlib.ueh.edu.vn

### ISSUE THREAD

**Issue by 31211027574** [UEHMonQAQC/23_902#261]
a. Trình duyệt web: Google Chrome phiên bản 116.0.5845.111 - Laptop: MSI Bravo 15 B5DD - Hệ điều hành: Windows 11
b. Kết quả thực tế: Đoạn mã ở dưới đây được thực hiện
c. Kết quả mong muốn: Đoạn mã ở dưới đây không được thực hiện
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang web smartlib.ueh.edu.vn
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/fa1e69d6-fcea-4f27-8111-ba3f29adae00)
ii. #2 Nhập bất kì kí tự nào ở trên thanh tìm kiếm:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/788e7a91-be6c-4667-9996-6c7e099b285d)
iii. #3 Truy cập tới mục "New search":
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/d18b7ee0-3c18-4cc5-89d2-d59e1f7acb89)
iiii. #4 Nhập đoạn mã dưới đây vào thanh tìm kiếm:
<script>alert('1')</script>
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/38b04d15-c866-4cce-9735-fbcf5fa9585b)
iiiii. #5 Kết quả như ở hình dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/70a5fb71-90cc-4a3a-b2ee-2ce429cbc0d1)

**Comment by 31211027582** [comment]
Trùng lỗi #260
