### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Thay đổi đường link URL - trang https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027574** [UEHMonQAQC/23_902#263]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Sau khi nhập link mà người dùng nhập thì nó không direct lỗi 404 mà nó quay lại trang chủ (thậm chí trang chủ không có giao diện hiện lên)
c. Kết quả mong muốn: Hệ thống không tiếp nhận đoạn mã và direct tới lỗi 404
d. Các bước thực hiện:
i. #1 Truy cập trang web smartlib.ueh.edu.vn:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/d84a516f-673f-43d1-a3e0-a75b9bb51647)
ii. #2 Thêm đuôi /book-search vào đằng sau của tên miền:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/fbdb285b-d585-4b5d-bb56-76cfebf80a2e)
(Đây là chức năng UEH Print Collection của trường)

iii. Thay đổi tên miền trên thêm bất kì kí tự nào:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/94e43bcc-0f6c-4bc4-a5d3-632e0d7b283d)
iiii. Đây là kết quả trả về sau khi nhập link:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/d8c26707-74b3-4838-8206-de73e037d02e)

**Comment by tquann286** [comment]
Đọc lại khái niệm về lỗi phi chức năng nha bạn
