### ISSUE TITLE
[Nhóm#04] - Lỗi giao diện - Lỗi không viết hoa đầu dòng- Trang https://caythuoc.vn 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#269]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Mục "nội dung" trong phần liên hệ không viết hoa đầu dòng
c. Kết quả mong muốn: Mục"nội dung" trong phần liên hệ viết hoa đầu dòng
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/3e820ff7-6a1e-4803-8982-c56160e7ffee">
ii. #1 Truy cập phần liên hệ, kéo xuống và quan sát mục "nội sung" không được viết hoa đầu dòng
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/e73f1eec-d959-4fb5-962a-ad72daa93820">

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/707ccf20-8c6a-4463-8e21-13591a71b816)
Không tìm thấy mục số điện thoại

**Comment by 31211027596** [comment]
Á nãy tui ghi lộn số điện thoại, nó là liên hệ á, mục nội dung trong phần liên hệ nó hông có viết hoa đầu dòng, tui sửa lại ròi nè, duyệt lại cho tui i

**Comment by 31211027613** [comment]
https://github.com/UEHMonQAQC/23_902/issues/141
