### ISSUE TITLE
[Nhóm#09] - Lỗi Phi chức năng - Lỗi Testing On Low-End Devices- Trang https://mwc.ueh.edu.vn

### ISSUE THREAD

**Issue by newbiecode123456** [UEHMonQAQC/23_902#276]
**Web Browser**
Google Chrome
**Các bước phát hiện lỗi**
1.	Giả lập thiết bị yếu - Why Mobile App Testing On Low-End Devices Is Important?
https://www.softwaretestinghelp.com/mobile-testing-low-end-devices/
2.	Giả lập thiết bị yếu – Kiểm tra tốc độ
 
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/ef4853d9-c1c0-4bfe-98f1-9ff8a5c484a1)

**Kết quả mong đợi**
Thiết bị đời cũ có thể truy cập với thời gian hợp lý
**Kết quả thực tế**
Load chận với thiết bị yếu

**Comment by tquann286** [comment]
Trang web chưa đủ lớn để có thể hỗ trợ các thiết bị yếu
