### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Lỗi cho phép đặt hàng khi không tick chọn phương thức thanh toán - Trang https://caythuoc.vn/ 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#285]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi đặt hàng, phương thức thanh toán mặc định được chọn sẵn là thanh toán khi nhận hàng, truy cập web element và sửa đổi thành "unChecked" hệ thống vẫn cho phép đặt hàng thành công
c. Kết quả mong muốn: Khi phương thức thanh toán là "unChecked" thì thông báo lỗi khi đặt hàng
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/1ab65403-d046-411f-8853-dab27bf325b5">
ii. Thêm 1 sản phẩm bất kì vào giỏ hàng và truy cập vào giỏ hàng
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/46da607d-35b1-4764-8f71-5bbcb41e497e">
iii. Điền thông tin vào form đặt hàng
![image](https://github.com/UEHMonQAQC/23_902/assets/142060841/ea0fad3c-b46c-41d4-bc96-cc01d6eddf56)
iiii. Mở inspect, truy cập vào element radio button của text thanh toán khi đặt hàng mục phương thức thanh toán đổi từ "checked" thành "unChecked"
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/0950b711-ddf2-4f4a-b82a-ea85b799f2d5">
iiiii. Nhấn đặt hàng và kết quả thành công
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/958494f1-aacf-411e-9a06-9df21769ea27">

**Comment by 31211027582** [comment]
Việc thay đổi trạng thái của radio từ 'checked' thành 'unChecked' bằng cách sử dụng Inspect Document. Điều này không phải là lỗi phi chức năng của hệ thống vì nó không xảy ra trong tình huống sử dụng bình thường của người dùng. Hệ thống hoạt động đúng chức năng khi người dùng sử dụng web mà không can thiệp.
