### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng- Đổi email đăng kí mà không cần xác nhận chính chủ - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027580** [UEHMonQAQC/23_902#288]
A. Web Browser: GoogleChrome 116.0.5845.111
B. Các bước phát hiện ra lỗi:
i. Truy cập trang web https://shop.ueh.edu.vn/my-account/ và đăng nhập ví dụ:
Tài khoản: Nhom8test
Mật khẩu: Nhom8test.
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/1966e219-4815-4dea-9e01-36153a48df87)
ii. Vào link tài khoản https://shop.ueh.edu.vn/my-account/edit-account/
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/5954467b-bb48-4b3b-9d31-3cb4ee8860c2)
iii. Đổi một tài khoản email thành một email khác chưa được tạo tài khoản ví dụ lailatestday@gmail.com
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/4f8f6434-476b-4c7a-baa4-195add7bcc96)
kết quả thông báo thành công
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/20b88483-1a22-4fa9-a934-8744463bbab3)
iv. Đăng xuất vào chọn quên mật khẩu, nhập tên tài khoản Nhom8test vào
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/f2acb077-0a81-47be-baa8-853116f7fd2f)
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/a93d7760-898f-483e-8717-c0d0f3fe7929)
C. Kết quả thực tế: email đổi mật khẩu thật sự được gửi qua email mới, và tài khoản dễ dàng bị lấy nếu chủ sở hữu không cẩn thận
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/27cd0153-9110-4353-bd96-85022c4404f1)
đây là link đổi mật khẩu một cách dễ dàng
![image](https://github.com/UEHMonQAQC/23_901/assets/142574592/0aba1d58-2d95-4f47-8290-6ae13d3a32d8)
D. Kết quả mong đợi: Cần phải gửi email xác nhận đổi tới email gốc hoặc yêu cầu nhập lại mật khẩu mới được quyền đổi.

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/5cda4798-49cd-4223-8488-e2b1d2b7901a)
Kết quả mong đợi không hợp lệ:
1. Đã đổi sang email mới thì việc gì lại gửi email khôi phục mật khẩu vào email cũ. Lỡ họ xoá email cũ thì sao, không đổi được mật khẩu luôn à.
2. `yêu cầu nhập lại mật khẩu mới được quyền đổi`: cực vô lí, đã chọn chức năng quên mật khẩu lại còn muốn nhập lại mật khẩu cũ.
