### ISSUE TITLE
[Nhóm#08] - Lỗi GUI- Lỗi chính tả - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027580** [UEHMonQAQC/23_902#289]
A. Web Browser: GoogleChrome 116.0.5845.111
B. Các bước phát hiện ra lỗi:
i. Truy cập trang web https://shop.ueh.edu.vn/chinh-sach/chinh-sach-bao-mat-thong-tin/
ii. Lướt xuống dưới
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/4b4c3a7c-a444-47a5-962f-c24d6fe714e9)
C. Kết quả thực tế Viết sai chính tả chữ thông
D. Kết quả mong muốn: Viết đúng chính tả

**Comment by 31211027598** [comment]
1 trang web chỉ chấp nhận 1 lỗi chính tả thôi nhé https://github.com/UEHMonQAQC/23_902/issues/73

Nếu trang web có 100 cái lỗi chính tả mà post lên hết thì tính là 100 lỗi ui sao được
