### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng- Lỗi load trang khi tràn ô tìm kiếm - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027580** [UEHMonQAQC/23_902#292]
A. Web Browser: GoogleChrome 116.0.5845.111
B. Các bước phát hiện ra lỗi:
i. Truy cập trang web https://shop.ueh.edu.vn/
ii. Chọn ô tìm kiếm nhập chuỗi kí tự dài tới khi tô tìm kiếm bị tràn và đứng web (chuỗi càng dài web đứng càng lâu)
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/e80fbd98-9976-4991-a50e-665c7e5dceaf)
C. Kết quả thực tế: trang web bị đứng và không thể thao tác gì ngoài scroll chuột, không thể refresh trang, không thể hồi phục ngay mà phải mất một khoản thời gian để trang hiện báo lỗi
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/00b52fe6-d3b6-4581-9817-3f626fd0f05f)
D. Kết quả mong muốn: Trang web giới hạn kí tự mà có thể chứa hoặc có thể nhanh chóng phục hồi sau khi bị tấn công và hiện thị kết quả tìm kiếm.
Video mình làm:
https://drive.google.com/file/d/1pfl53fRRGxn2bMSlUmbR3DYC5I3SNrBW/view

**Comment by tquann286** [comment]
1. Vui lòng đọc lại khái niệm lỗi phi chức năng
2. Đã test theo và không thấy lỗi gì, trang web vẫn hoạt động bình thường
