### ISSUE TITLE
[Nhóm#08] - Lỗi GUI - Màu sắc không đủ tương phản - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027580** [UEHMonQAQC/23_902#293]
A. Web Browser: GoogleChrome 116.0.5845.111
B. Các bước phát hiện ra lỗi:
i. Truy cập trang web https://shop.ueh.edu.vn/
ii. Đưa trỏ chuột vào ô tìm kiếm sẽ thấy con trỏ chuột bị tàng hình
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/42768970-b100-4aef-8555-96aa6b23a759)
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/1b7a752f-0744-4f8c-a6da-3f37e6eb9472)
C. Kết quả thực tế: Con trỏ chuột rất nhỏ nên dễ bị biến mất khỏi màn hình
D. Kết quả mong muốn: Làm màu tương phản để hỗ trợ người dùng dễ nhìn hơn
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/3a02a687-67eb-4ff6-aa10-e3d9d57c4736)

**Comment by tquann286** [comment]
![384156406_836480454786280_7989836564866290152_n](https://github.com/UEHMonQAQC/23_902/assets/88314050/60b09964-8759-4fa8-a982-74911d79b95f)
- Đã test theo và ui vẫn ổn, vẫn thấy chuột bình thường
- Mình có để ý vài lần ở các trang web khác lâu lâu chuột sẽ bị biến mất, lỗi này là do window nhé
