### ISSUE TITLE
[Nhóm #04] - Lỗi phi chức năng - Lỗi không phản hồi khi tìm kiếm quá số lượng từ  - https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#296]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Trang web không phản hồi với các tìm kiếm dài trên 1000 từ.
c. Kết quả mong muốn: Web hiển thị không tìm thấy sản phẩm hoặc trả về lỗi tìm kiếm quá dài.
d. Các bước phát hiện lỗi:
i. #1 Truy cập vào website https://smartlib.ueh.edu.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/b7937943-1d06-4ac9-a112-61d7a1f8b4d4">
ii. #1 Nhập vào ô tìm kiếm với hơn 1000 kí tự và click tìm kiếm, trang web không phản hồi
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/be3adc86-cd12-4985-a759-23f7f5cf2db9">

**Comment by 31211027582** [comment]
Khi tìm kiếm quá nhiều từ (ví dụ: 1000 từ), trang web có thể không xử lý được nhanh hoặc không phản hồi. Điều này không phải lỗi phi chức năng. Thay vào đó, nó có thể do trang web không được tối ưu hóa để xử lý tìm kiếm lớn hoặc có giới hạn trong việc xử lý tìm kiếm này.
