### ISSUE TITLE
[Nhóm #04] - Lỗi phi chức năng - Perfomance của trang trên điện thoại ở mức thấp - https://smartlib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#297]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Chỉ số hiệu suất Perfomance ở mức rất thấp (đỏ)
c. Kết quả mong muốn: Chỉ số Perfomance đạt yêu cầu (mức trung bình hoặc cao)
d. Các bước phát hiện lỗi:
i. #1 Truy cập vào website https://smartlib.ueh.edu.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/b7937943-1d06-4ac9-a112-61d7a1f8b4d4">
ii. #1 Chuột phải chọn inspect
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/1aa05cbf-eaa9-41f1-a52f-0d871e2bdc24">
iii. #1 Trong Inspect chọn công cụ Lighthouse, chọn thiết bị mobile
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/dbdff464-d95f-4b90-948e-0182b108ae61">
iiii. Chọn Analyze page load, quan sát kết quả cảnh báo.
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/716f50bc-5fb7-4498-9ef4-28711d9de9c4">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/137f1f50-01e9-4d89-a218-78114b3e9090">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/4ce2e818-5aa4-4e62-a1f4-b87a9b703c1b">

**Comment by tquann286** [comment]
tương tự https://github.com/UEHMonQAQC/23_902/issues/299#issuecomment-1734869276
