### ISSUE TITLE
[Nhóm #04] - Lỗi phi chức năng - Perfomance của trang trên điện thoại ở mức thấp - https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#298]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Chỉ số hiệu suất Perfomance ở mức rất thấp (đỏ)
c. Kết quả mong muốn: Chỉ số Perfomance đạt yêu cầu (mức trung bình hoặc cao)
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang web caythuoc.vn
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/8b17a388-3dd1-4792-9385-6c2ab15a6f70">
ii. #1 Chuột phải chọn inspect
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/75d9f913-359a-4458-88d6-c0b101efe075">
iii. #1 Trong Inspect chọn công cụ Lighthouse, chọn thiết bị mobile
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/b623fc3e-72a9-436d-9934-0150056d30b7">
iiii. #1 Chọn Analyze page load, quan sát kết quả cảnh báo.
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/60a175c5-8cd0-46aa-b54b-e6dcc634000d">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/be6b5770-248c-41a5-b394-d36ef94e99ce">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/4ce22eb0-e4ad-483a-b8b7-5ecaa5fbbad5">

**Comment by tquann286** [comment]
tương tự https://github.com/UEHMonQAQC/23_902/issues/299#issuecomment-1734869276
