### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Perfomance của trang trên web ở mức thấp - https://smartlib.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#299]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Chỉ số hiệu suất Perfomance ở mức rất thấp (đỏ)
c. Kết quả mong muốn: Chỉ số Perfomance đạt yêu cầu (mức trung bình hoặc cao)
d. Các bước phát hiện lỗi:
i. #1 Truy cập vào website https://smartlib.ueh.edu.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/b7937943-1d06-4ac9-a112-61d7a1f8b4d4">
ii. #1 Chuột phải chọn inspect
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/1aa05cbf-eaa9-41f1-a52f-0d871e2bdc24">
iii. #1 Trong Inspect chọn công cụ Lighthouse, chọn thiết bị desktop
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/d95ae0c1-bc23-43d8-93dc-3cecd447fc7e">
iiii. Chọn Analyze page load, quan sát kết quả cảnh báo.
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/415751cc-6748-4605-8cbd-90862af251b9">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/e42fa2fe-bd9d-41f6-a04e-1e489f09d851">
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/2412708b-64ec-4a5a-8cf6-2af3b930ea38">

**Comment by tquann286** [comment]
Như thầy đã nói thì đây là công cụ dành cho developer, tức chỉ là một tools, mới chỉ đưa ra WARNING chứ chưa phải lỗi. Nên cần cụ thể hoá việc trang web tải bị chậm (trải nghiệm thực tế), hoặc chức năng bị ảnh hưởng (vd như tấn công bằng DDOS,...)
