### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi không đọc được báo in - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#30]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
b.Kết quả thực tế: Lỗi hiển thị trang báo
c. Kết quả mong muốn: không bị lỗi hiển thị
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào Chọn biểu tượng đọc báo in
<img width="93" alt="Screenshot 2023-08-27 170529" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/fdcecacb-f634-44ab-b166-2ad4126710ed">
ii. #2 Nhấn chọn trang Báo Lâm đồng thứ Sáu ngày 08-2023

<img width="354" alt="Screenshot 2023-08-27 170735" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/4c290f12-d6c5-4b97-9ed0-cdca01ab0c1d">

iii. #3 Nhấn chọn biểu tượng “Viền/Dấu trang”

<img width="395" alt="Screenshot 2023-08-27 170910" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/703171da-de9b-4654-b085-54d87eef010e">

iv. #4 Khi nhấn chọn dấu trang để đọc thì trang báo không hiển thị
<img width="952" alt="Screenshot 2023-08-27 165520" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/eac8c259-7a1d-4d62-9c07-283f4ed4bd63">

<img width="953" alt="Screenshot 2023-08-27 165540" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/ba4940e5-0255-4289-b063-ebb73a592ca7">

**Comment by 31211027582** [comment]
Mình check lại thì vẫn đọc được nhe
