### ISSUE TITLE
[Nhóm#05] - Lỗi GUI -  footer không hiển thị hết - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#303]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.

Thiết bị: PC DELL OPTIPLEX ALL IN ONE 7490 ( máy tính ở phòng máy trường )
Hệ điều hành : Win 10
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: footer không hiển thị hết so với trang để một khoảng trống rất lớn
c. Kết quả mong muốn: footer hiển thị lấp đầy trang không chừa lại khoảng trống
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang[ https://cpv.ueh.edu.vn/index.php?m=contact](https://cpv.ueh.edu.vn/index.php?m=contact)
ii. Nhận thấy footer hiển thị lấp đầy trang không chừa lại khoảng trống
<img width="499" alt="Screenshot 2023-09-26 132525" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/9ca5fcb3-71e9-4c9a-866e-f14757a1cbb4">

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/44b2f3ad-486b-4eec-bb30-23d0f7c6f838)
nội dung trang ít nên việc footer ở giữa màn hình vẫn hợp lí, không ảnh hưởng đến người dùng, nếu để `footer hiển thị lấp đầy trang không chừa lại khoảng trống` thì khả năng nhìn cũng rất là kì
