### ISSUE TITLE
[Nhóm#05] - Lỗi GUI -  Hình ảnh ở mục trình chiếu bị giãn - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#306]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
Thiết bị: PC DELL OPTIPLEX ALL IN ONE 7490 ( máy tính ở phòng máy trường )
Hệ điều hành : Win 10
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: hình ảnh ở mục trình chiếu bị giãn ra
c. Kết quả mong muốn: hình ảnh ở mục trình chiếu đúng kích thước vừa khung hình
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang https://cpv.ueh.edu.vn/
ii. Nhận thấy ở phần trình chiếu hình ảnh “ Không gian văn hóa Hồ Chí Minh” bị giãn hình so với hình thực tế sau khi click vào
<img width="348" alt="Screenshot 2023-09-26 133218" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/f1550194-e6d7-45b2-a5c4-629c63c305d3">
<img width="428" alt="Screenshot 2023-09-26 133228" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/94981797-3d86-4544-a2ae-04c9401b3572">

**Comment by 31211027598** [comment]
Hình ảnh giãn ra để phù hợp với kích thước của khung tìm kiếm, hình ảnh vẫn nhìn tốt, không gây vỡ hình ảnh hay ui
