### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng -  Lỗi "ERR_CACHE_MISS" không thể tìm thấy dữ liệu - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#307]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
Thiết bị: PC DELL OPTIPLEX ALL IN ONE 7490 ( máy tính ở phòng máy trường )
Hệ điều hành : Win 10
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: Lỗi "ERR_CACHE_MISS" không thể tìm thấy dữ liệu đã được lưu trữ trong bộ nhớ cache.
c. Kết quả mong muốn: sau khi quay về thì load đường dẫn đã truy cập trước đó
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang https://cpv.ueh.edu.vn/
ii. Nhập bất kỳ kí tự gì ở ô tìm kiếm thì đều dẫn ra đường link ở dưới , ví dụ “a”

<img width="274" alt="Screenshot 2023-09-26 135021" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/beb48bd7-6004-4d0f-9f71-22966aa3ff5b">
<img width="496" alt="Screenshot 2023-09-26 135037" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/7c59d2a5-bd2c-452b-8691-183bb3721f98">

iii.Chọn vào bất kì đường dẫn khác sau đó bấm “Back” về thì hiển thị lỗi không thể tìm dữ liệu

<img width="499" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/b2ed1772-844d-4c6a-80ac-2a080565cf5a">

**Comment by 31211027598** [comment]
trùng https://github.com/UEHMonQAQC/23_902/issues/308
