### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Không xuất kết quả từ khóa muốn tìm kiếm - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#310]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
Thiết bị: PC DELL OPTIPLEX ALL IN ONE 7490 ( máy tính ở phòng máy trường )
Hệ điều hành : Win 10
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: Kết quả tìm kiếm chỉ có vài đường dẫn có liên quan đến từ khóa muốn tìm kiếm
c. Kết quả mong muốn: Kết quả xuất ra có chứa từ khóa muốn “tìm kiếm”
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang https://cpv.ueh.edu.vn/
ii. Nhập từ khóa “ lịch sử” ở ô tìm kiếm rồi bấm “enter”  xuất ra kết quả bên dưới, chỉ có 4/13 mục có chứa “ lịch sử”
<img width="452" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/f6b21d1b-5d79-4255-bec1-f3d17158acb6">

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/6a956dbc-6832-4dd2-87a0-dcbed9d0678e)
mình truy cập vào các trang web không có lịch sử ở title (màn tìm kiếm) nhưng vẫn có chữ lịch sử ở nội dung nhé, điều này hoàn toàn hợp lí.

Thậm chí nếu nội dung không có chữ hợp lí nhưng vẫn nói về lịch sử thì vẫn nên hiện ra cho user
ví dụ như các web lớn như youtube, facebook sẽ dễ dàng nhận thấy điều này khi tìm kiếm.

Lỗi này sẽ được tính nếu: Nội dung bài viết không liên quan gì đến từ khoá tìm kiếm
