### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi không tương thích hiển thị trên điện thoại  - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#311]
a. Web Browser: Chrome 117.0.5938.60
Thiết bị: Điện thoại samsung note20
Hệ điều hành : Android 13
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: Không tương thích khi hiển thị trên điện thoại
c. Kết quả mong muốn: Hiển thị kết quả tương thích khi hiển thị trên điện thoại
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang https://cpv.ueh.edu.vn/
ii.#2 Trang thủ dư khoảng trống và logo bị đẩy về phía bên dưới , vào mục kế hoạch thấy kích cỡ chữ lớn hơn so với mục tiêu đề

<img width="162" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/81d1b35a-e3e5-460b-93f8-70e5d4ada683">

<img width="151" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/35ec9989-147b-4667-9862-fd77b6601276">

iii.#3 đổi chế độ hiển thị ngang thì trở về hiện thị bình thường đúng so với khi truy cập bằng máy tính

<img width="661" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/201648b4-2082-4924-9125-ffb12505dd90">

<img width="663" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/c86e6d64-d7b6-4f6e-a2d7-8c6d1f72a8ef">

**Comment by tquann286** [comment]
![image](https://github.com/UEHMonQAQC/23_902/assets/88314050/22ba46a1-afc6-4d74-ba14-1131f4a211a1)
1.  Điện thoại sao lại 23.8 inch
2.  Đây không phải lỗi chức năng
3.  Mình thấy giao diện trên điện thoại vẫn ổn, không bị che lấp hay mất chữ ảnh hưởng UI
