### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi không có trang đích ở mục trình chiếu - Trang http://www.cpv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#313]
a. Web Browser: Microsoft Edge Version 115.0.1901.203.
Thiết bị: PC DELL OPTIPLEX ALL IN ONE 7490 ( máy tính ở phòng máy trường )
Hệ điều hành : Win 10
Kích cỡ màn hình: 23.8inch
b. Kết quả thực tế: không có trang đích ở mục trình chiếu 
c. Kết quả mong muốn: các mục trình chiếu nội dung chính đều có trang đích còn hoạt động
d. Các bước thực hiện lỗi: 
i. #1 Truy cập trang https://cpv.ueh.edu.vn/
ii.#2 chọn các mục hình ảnh ở phần trình chiếu hình ảnh, thì chỉ có “ Không gian văn hóa Hồ Chí Minh” dẫn đối trang web đích còn lại không có dữ liệu hoặc refresh lại trang chủ

![image](https://github.com/UEHMonQAQC/23_902/assets/143202929/5d8b3305-da5a-435f-8eb6-d25297baf44c)

![image](https://github.com/UEHMonQAQC/23_902/assets/143202929/4189a4d2-de72-427a-a57f-01580266f4c9)

**Comment by tquann286** [comment]
Các hình ảnh kia chỉ để trang trí trang web, nên việc không dẫn đến trang khác thì vẫn bình thường, khi nào bấm vào mà gây ra lỗi ảnh hưởng đến trang web, hoặc lúc bấm được lúc không,... thì sẽ tính lỗi
