### ISSUE TITLE
[Nhóm#07] - Lỗi chức năng - Số điện thoại nhận bất kỳ thông tin nào - Trang https://gamevui.vn/

### ISSUE THREAD

**Issue by 31211027623** [UEHMonQAQC/23_902#317]
a. Web browser: Google Chrome (Phiên bản 117.0.5938.92 (Phiên bản Chính thức) (64 bit))
b. Các bước phát hiện lỗi:
i. Mở trình duyệt web và truy cập: https://gamevui.vn/
ii. Đưa trỏ chuột tới phần liên hệ dưới trang web
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/e5e01b59-46b0-4d06-a37a-af3f08236d5f)
iii. Điền bất cứ dạng thông tin nào vào mục số điện thoại như hình bên dưới và nhấn lưu thông tin
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/a9a72d49-2e3d-456b-8e26-1f8326295c3a)
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/0d73cf6c-8af6-42f4-9c01-9ec5a6820cd1)
c. Kết quả thực tế: Có thể cập nhật bất cứ dạng thông tin nào vào mục số điện thoại
d. Kết quả mong muốn: Hiển thị thông báo lỗi khi nhập sai cấu trúc thông tin

**Comment by tquann286** [comment]
Này chỉ là một form liên hệ nên việc validate số điện thoại không cần thiết và không gây ảnh hưởng hay lỗi gì đáng kể để xác nhận lỗi
