### ISSUE TITLE
[Nhóm#01] – Lỗi Giao Diện – Hiển thị không đồng bộ – Trang https://alumni.ueh.edu.vn/

### ISSUE THREAD

**Issue by QuanTrinhUEH** [UEHMonQAQC/23_902#318]
a. Web Browser: Cốc Cốc phiên bản 121.0.188
b. Các bước để phát hiện lỗi:
i. Chọn trình duyệt và vào cài đặt của Cốc Cốc bật chế độ Duyệt web chế độ tối
ii. Vào trang web https://alumni.ueh.edu.vn/ kéo xuống cuối trang và phát hiện lỗi
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/aa4ebb10-1672-49c8-875f-7bd35412891c)
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/dac3a6a8-78c7-4c8c-b10f-db16dc81d761)
c. Kết quả thực tế: Màu bản đồ hiển thị không đồng bộ
d. Kết quả mong đợi: Bản đồ hiển thị rõ ràng, đồng bộ

**Comment by tquann286** [comment]
Lỗi này là do cốc cốc nha
