### ISSUE TITLE
[Nhóm#06] - Lỗi giao diện - Lỗi không hiển thị ảnh - trang https://govirlunteer.ueh.edu.vn/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#320]
a. Web Browser: Google Chrome Version 116.0.5845.111
b. Các bước phát hiện lỗi 
i. #1: Truy cập trang govirlunteer.ueh.edu.vn sau đó cuộn tới chỗ như hình 

![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/f0d34b10-244b-402b-9771-97f9ce882ca7)

c. Kết quả thực tế: Hình ảnh bị lỗi không hiển thị được
d. Kết quả mong đợi: Hình ảnh hiển thị bình thường không bị lỗi

**Comment by 31211027613** [comment]
Lỗi này đang bị trùng với https://github.com/UEHMonQAQC/23_902/issues/148 nhé nhóm ơi
