### ISSUE TITLE
[Nhóm#01] – Lỗi Chức Năng – Lỗi tìm kiếm - Trang https://daklak24h.com.vn/

### ISSUE THREAD

**Issue by QuanTrinhUEH** [UEHMonQAQC/23_902#324]
a. Web Browser: Cốc Cốc phiên bản 121.0.188
b. Các bước để phát hiện lỗi:
i. Truy cập trang web: https://daklak24h.com.vn/ bằng trình duyệt
ii. Nhấp vào ô Tìm kiếm và để trống sau đó bấm tìm kiếm
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/086e02a1-3238-4b73-aa56-4eb0e9696a88)
iii. Trang web vẫn hiển thị ra kết quả
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/6748a6c3-0211-471a-8da6-643985052bfb)
c. Kết quả thực tế: Trang web hiển thị ra các bài báo mặc dù để trống ô tìm kiếm
d. Kết quả mong đợi: Thông báo không được để trống ô tìm kiếm hoặc không có bài báo phù hợp

**Comment by tquann286** [comment]
Đã chốt lỗi vào ngày 27/9

**Comment by tquann286** [comment]
Vẫn ổn, khi nào bị lỗi trắng trang hoặc ra kết quả tìm kiếm khác với từ khoá tìm kiếm mới lỗi
