### ISSUE TITLE
[Nhóm#01] Lỗi giao diện – Lỗi không đồng nhất font chữ - Trang https://daklak24h.com.vn/

### ISSUE THREAD

**Issue by QuanTrinhUEH** [UEHMonQAQC/23_902#326]
a. Web Browser: Cốc Cốc phiên bản 121.0.188
b. Các bước để phát hiện lỗi:
i. Truy cập vào trang web https://daklak24h.com.vn/ bằng trình duyệt
ii. Chọn 1 bài báo bất kỳ
Font đồng bộ:
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/1cc6533b-9145-4a03-9993-6e5a851ca933)
Font không đồng bộ:
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/f33dbc94-cea7-44a2-a6d7-9e9cc3761e51)
![image](https://github.com/UEHMonQAQC/23_902/assets/143281625/83dbab2a-8873-4588-ad3a-5a3b9623a167)
c. Kết quả thực tế: Không đồng bộ về font chữ
d. Kết quả mong đợi: Thống nhất về font chữ

**Comment by tquann286** [comment]
Đã chốt lỗi vào ngày 27/9

**Comment by tquann286** [comment]
Việc sử dụng font chữ nào hoàn toàn phụ thuộc vào design nha. Designer bắt dùng font nào thì dev phải dùng font chữ đó. Lỗi này sẽ được chấp nhận nếu: Bạn có bản thiết kế của trang web, và chỉ ra được 1 chỗ sử dụng font chữ khác với design
