### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng – Lỗi ClickJacking - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#328]
a. Web Browser: Google Chrome
b. Các bước phát hiện lỗi
1. Nhúng iframe web https://khdtkt.ueh.edu.vn/ và các thuộc tính, mã html như hình bên dưới vào một trang web lừa đảo 
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/46f594f0-0f74-40b6-8c25-48556f435179)
2. Kết quả như hình bên dưới
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/09c09134-552b-4f0f-a2cc-bed472770cd0)
c. Kết quả thực tế: các hacker có thể lừa người dùng vào một trang web với tên miền tương tự và giao diện giống như trang web chính, từ đó đánh cấp thông tin người dùng
d. Kết quả mong đợi: Trang web phải có biện pháp bảo đảm an toàn cho thông tin người dùng

**Comment by 31211027598** [comment]
@31211027573 Lỗi post trễ.
