### ISSUE TITLE
[Nhóm#08] - Lỗi Chức năng -Không xác thực trường dữ liệu số điện thoại - Trang https://shop.ueh.edu.vn

### ISSUE THREAD

**Issue by thientruc1691997** [UEHMonQAQC/23_902#329]
a. Web browser: Chrome
b. Các bước thực hiện: 
- Dùng TK sinh viên UEH, đăng nhập -> https://shop.ueh.edu.vn/
- Chọn mặt hàng bất kỳ cần mua
- Vào giỏ hàng, nhập thông tin nhận hàng
- Nhập số điện thoại: 123456789
<img width="1271" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/117527214/4a365815-4c54-4b52-a95f-634cfe1c394e">

c. Kết quả thực hiện: Lưu thông tin thành công
d. Kết quả mong muốn: ràng buộc dữ liệu số điện thoại: 10 chữ số, bắt đầu bằng số 0.

**Comment by 31211027613** [comment]
Dạ em thấy lỗi trên khá tương tự như lỗi dưới đây ạ https://github.com/UEHMonQAQC/23_902/issues/129
