### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - Lỗi ClickJacking - Trang https://truong.hcm.edu.vn

### ISSUE THREAD

**Issue by thientruc1691997** [UEHMonQAQC/23_902#330]
a. Web browser: Google Chrome
b. Mô ta các bước thực hiện:
- Dùng security scanner -> được kết quả như hình bên dưới
<img width="1203" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/117527214/ceba10f3-f3aa-4f7b-bee2-4ff2442d3e36">

- Nhúng iframe web truong.hcm.edu.vn vào 1 website fake khác, yêu cầu nhập username và password
c. Kết quả thực hiện
<img width="1431" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/117527214/73bc60c9-534d-4845-a1b6-c86ba766208c">

d. Kết quả mong đợi:
Chống chèn trang web vào trang web khác bằng iframe

**Comment by tquann286** [comment]
E thấy issue này up ngày 30 nên được tính là trễ hạn deadline, nếu chị vẫn muốn tính lỗi này thì sẽ bị trừ 1đ theo [quy định](https://docs.google.com/spreadsheets/d/1KhlcmlZNROZPuQoBupFZPvOM6czEHwOa/edit#gid=1148740518), như vậy thì chị sẽ bị lỗ 0.5đ, nếu chị kiếm được nhiều lỗi hơn để gỡ lại cho có lời nha. Còn nếu chỉ kiếm được 1 lỗi này thì em nghĩ c nên xoá issues này.

**Comment by thientruc1691997** [comment]
Mong các bạn QA tính thêm lỗi phi chức năng này cho nhóm 8. Có gì chị sẽ email xin thầy thêm. Cảm ơn em nhiều.

**Comment by 31211027613** [comment]
Dạ em và các bạn sẽ thêm lỗi này vào KPI lỗi PCN của nhóm 8 và không trừ điểm trễ deadline khi có được hình mail thầy chấp nhận không trừ điểm. Em cảm ơn chị nhiều @thientruc1691997

**Comment by 31211027613** [comment]
Cho em hỏi là kết quả của thầy về lỗi này như thế nào rồi ạ.

**Comment by thientruc1691997** [comment]
Chưa thấy thầy phản hồi á em

**Comment by 31211027613** [comment]
Dạ em thấy cũng gần tới hạn nộp đồ án rồi ấy chị, nên em xin phép đóng lỗi để có thể thống kê lỗi được chính xác hơn được không chị. Em cảm ơn
=

**Comment by thientruc1691997** [comment]
Oki em
