### ISSUE TITLE
[NHÓM#07]- Lỗi GUI - Lỗi Responsive- trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#38]
Bug: Lỗi hiển thị trang web khi thu hẹp màn hình trình duyệt 
Web browser: Google Chrome
Các bước phát hiện lỗi:
#1.kéo màn hình trình duyệt ở trang chủ hẹp lại ở độ rộng từ 970 - 1180px
Kết quả thực tế: các label trong thanh menu bị xuống dòng dẫn đến việc thanh menu lấn đi một phần tiêu đề ở bên dưới
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/a1907a7e-ec2f-4d1a-a91a-c95f30e1f79e)

Kết quả mong đợi: web sẽ hiển thị một cách chính xác khi kích thước màn hình bị thu hẹp, thanh menu sẽ không che khuất dòng nội dung của title bên dưới

Bug: Lỗi hiển thị item cuối cùng trên thanh menu và nút tìm kiếm bị dính    vào nhau
web browser: Google Chrome
Các bước phát hiện lỗi:
#1. kéo màn hình xuống cho đến khi qua khỏi thanh menu
#2. thanh menu sẽ tự hiện ra lại và bị lỗi hiển thị ở đoạn cuối thanh

Kết quả thực tế: item cuối cùng của thanh menu là “Liên hệ” bị sát vào nút tìm kiếm
Kết quả mong đợi: nó sẽ hiển thị có khoảng cách như khoảng cách giữa những item khác trong thanh menu

**Comment by 31211027598** [comment]
Bị trùng với lỗi GUI đã post lên trước đó
https://github.com/UEHMonQAQC/23_902/issues/37
