### ISSUE TITLE
[Nhóm#07] - Lỗi GUI - Lỗi Các thông tin bị ẩn mất khi phóng to 175% - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027619** [UEHMonQAQC/23_902#39]
a. Web browser : Google Chrome
b. Các bước phát hiện lỗi:
i. Chọn trình duyệt và đăng nhập vào https://khdtkt.ueh.edu.vn/
ii. Phóng to đến 175% sẽ xuất hiện tình trạng biến mất như hình dưới đây:
![GUI2_B1](https://github.com/UEHMonQAQC/23_902/assets/141991513/ac954838-f55a-4ea2-8e0a-b9e1cda45735)

c. Kết quả thực tế: Khối các thông tin tìm kiếm căn bản bị biến mất
d. Kết quả mong muốn: Khối vẫn tồn tại sẽ xuất hiện mà không biến mất

**Comment by 31211027598** [comment]
Đây là tính năng làm web khi phóng to đến một mức độ, sẽ xuất hiện nút Menu. Khi bấm vào sẽ xuất hiện các khối thông tin tìm kiếm căn bản.
Đây là một tính năng của nhà phát triển, khi làm giao diện web trên điện thoại. Thay vì để các khối tìm kiếm, người dùng có thể vào menu chọn mục cần tìm rồi sau đó đóng lại sẽ đỡ mất không gian trên điện thoại.
Thêm vào đó ta không được phóng to hay thu nhỏ trang, vì sẽ gây ra một số lỗi về giao diện không đáng có.
Ta phải sử dụng các thiết bị khác mở trang web, nếu mặc định mà xảy ra lỗi về giao diện thì sẽ được chấp nhận.
