### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Không dùng được chức năng đọc báo trên file pdf liên kết với website- trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by BNah1** [UEHMonQAQC/23_902#4]
a. Web Browser: Microsoft Edge Version 115.0.1901.203. 
b.Kết quả thực tế: không đọc được dữ liệu pdf.
c. Kết quả mong muốn: Kết nối file đọc báo
d. Các bước phát hiện lỗi: 
i. #1 Truy cập trang http://www. http://baolamdong.vn/ vào chọn vào mục “ đọc báo in”
 ![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/0442c38f-03ab-4e95-9c65-3604a0e9a45f)
ii. #2 Chọn bài báo ngày 19/08/2023 

![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/35840ebd-cae2-4521-a49a-cba57db2f21e)

iii. #3  Kết quả trả về thông báo lỗi tải file.
![image](https://github.com/UEHMonQAQC/23_902/assets/111131182/515ca37c-ee2a-4325-8f1c-adf7e474a3a6)

**Comment by 31211027582** [comment]
Mình check lại thì vẫn access được nhe
![image](https://github.com/UEHMonQAQC/23_902/assets/142146180/dd4a1d13-ef61-4219-ad5e-c5af8e48a4df)
