### ISSUE TITLE
[NHÓM#07]- Lỗi Phi Chức Năng - Load trang web chậm- trang https://khdtkt.ueh.edu.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#42]
Bug: Load trang web chậm
web browser: Google Chrome
Các bước phát hiện lỗi:
sử dụng công cụ Google Lighthouse để đo hiệu suất
#1. truy cập trang Web
#2. Mở cửa sổ kiểm tra của trình duyệt (F12)
#3. Trên thanh công cụ vào tab Lighthouse
#4 Ở phần Categories chọn Performance và ấn nút Analyze page load
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/48f47db3-e020-4d6c-b471-aa95be2ae97a)

Kết quả thực tế: 
![image](https://github.com/UEHMonQAQC/23_902/assets/142142216/1ad60dea-435a-4632-be6e-dd714bbf6272)
	
Mất 3.6s để Load được nội dung đầu tiên của trang web
Phần nội dung quan trọng nhất phải mất 5.1s để hiển thị
Kết quả mong đợi: phải cung cấp thông tin nhanh chống cho người dùng.

**Comment by 31211027598** [comment]
@31211027573  Mình thấy đây không phải là một lỗi phi chức năng vì:
- Công cụ Google lighthouse đo tốc độ load trang web chậm hơn lúc truy cập bình thường.
- Mỗi lần sử dụng tiện ích này sẽ cho ra kết quả khác nhau do đường truyện mạng cũng là một phần.
- Trong lỗi phi chức năng tốc độ thực hiện chức năng làm hệ thống bị treo phải hơn 3 phút.
![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/cad0e3b8-39e0-4ee6-831a-f184e0e34d01)
