### ISSUE TITLE
[Nhóm#07] - Lỗi GUI - Lỗi bố cục không đồng đều - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027625** [UEHMonQAQC/23_902#45]
a. Web Browser: Google Chrome 116.0.5845.111 ( Bản chính thức)(64bit)
b. Các bước để phát hiện lỗi:
   i. #1: Chọn trình duyệt và đăng nhập vào https://khdtkt.ueh.edu.vn/
  ii. #2 Từ trang chủ -  Đăng ký giảng đường - Chọn buổi. Xuất hiện lỗi:
![image](https://github.com/UEHMonQAQC/23_902/assets/143168942/371e0b95-081b-45b6-bf2e-562380e1096a)
c. Kết quả thực tế: Phân chia bố cục không đồng đều dẫn đến việc thừa khoảng trắng lớn ở phía dưới
d. Kết quả mong đợi: Phân chia bố cục đồng đều, cắt giảm diện tích phần thừa

**Comment by 31211027598** [comment]
Đây không phải lỗi GUI, đây là do thiết kế của bộ phận phát triển. Khi chọn xong, bảng chọn sẽ tắt và có thể thao tác với các thành phần khác một cách bình thường.
