### ISSUE TITLE
[Nhóm#07] - Lỗi chức năng - Lỗi nhấn vào button thông báo nhưng không thực hiện chức năng - Trang https://gamevui.vn/ 

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#53]
a. Web Browser: Microsoft Edge Version 116.0.1938.54 (Official build) (64-bit)
b. Các bước để phát hiện lỗi:
i. #1: Vào trang  [https://gamevui.vn/](url)
ii. #2: Nhấn vào button chuông thông báo
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/747d5f34-056d-4cf8-b707-107fbb21dbbf)

c. Kết quả thực tế: Không hiển thị thông báo.
d. Kết quả mong đợi: Có thể hiện thị thông báo của trang.

**Comment by 31211027598** [comment]
@31211027599 Có thể là trang chưa có thông báo gửi đến người dùng.
![image](https://github.com/UEHMonQAQC/23_902/assets/142154104/711de8ef-1266-4a75-ab57-ba6e5a2226a5)

**Comment by phatleework7** [comment]
@31211027598  Mình mới kiểm tra lại do mình dùng extension chặn quảng cáo nên không hiển thị được thanh thông báo khi bật vào.

**Comment by 31211027598** [comment]
OK
