### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Không có thuộc tính "alt" trong thẻ img - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027619** [UEHMonQAQC/23_902#66]
a. Web browser: Google Chrome
b. Các bước phát hiện lỗi:
i. Mở trình duyệt web và truy cập trang web https://validator.w3.org/
ii. Thêm đường link https://khdtkt.ueh.edu.vn/ vào mục Address
![PCN3_B1](https://github.com/UEHMonQAQC/23_902/assets/141991513/d6288279-a2f4-4df3-8397-56b695a589cc)
iii. Tìm đến dòng thứ 23 sẽ xuất hiện lỗi alt
![PCN3_B2](https://github.com/UEHMonQAQC/23_902/assets/141991513/f0dab7e4-93d1-4d96-a966-ca7bf43edc86)
c. kết quả thực tế: Xuất hiện lỗi thiếu thuộc tính "alt"
d. Kết quả mong muốn: Thêm thuộc tính "alt" vào img

**Comment by 31211027619** [comment]
![ChungMinh1](https://github.com/UEHMonQAQC/23_902/assets/141991513/c3b67fac-3a0f-4fdd-9b1c-f819f876514b)

Khái niệm test Non Function

**Comment by 31211027598** [comment]
@31211027619 
Thuộc tính alt cho thẻ <img> không nhất thiết phải có, nếu có thì chỉ là cho đúng cấu trúc của thẻ.
Thuộc tính alt này chỉ hoạt động khi hình ảnh của thẻ <img> đó không hiển thị. Nhưng ở trang khdtkt.ueh.edu.vn sử dụng đường dẫn tương đối, nên sẽ không lo về việc không hiển thị logo.
Vậy nên đây không phải là 1 lỗi phi chức năng.
