### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Không có thuộc tính "alt" trong thẻ img - Trang https://gamevui.vn/

### ISSUE THREAD

**Issue by 31211027619** [UEHMonQAQC/23_902#67]
a. Web browser: Google Chrome
b. Các bước phát hiện lỗi:
i. Mở trình duyệt web và truy cập trang web https://validator.w3.org/
ii. Thêm đường link https://gamevui.vn/ vào mục Address
![PCN4_B2](https://github.com/UEHMonQAQC/23_902/assets/141991513/44022445-6d9a-4db2-8b16-e273dfcbde93)
iii. Sẽ tìm thấy xuất hiện hàng loạt lỗi alt
![PCN4_B1](https://github.com/UEHMonQAQC/23_902/assets/141991513/6c458763-eee2-4891-88f0-ef17d12c0320)

c. kết quả thực tế: Xuất hiện lỗi thiếu thuộc tính "alt"
d. Kết quả mong muốn: Thêm thuộc tính "alt" vào img

**Comment by 31211027598** [comment]
@31211027619 
Đây cũng không phải một lỗi phi chức năng do thiếu thuộc tính alt cho thẻ <img> như đã giải thích ở https://github.com/UEHMonQAQC/23_902/issues/66#issuecomment-1695497184
