### ISSUE TITLE
[Nhóm#07] - Lỗi Phi chức năng - Không có mã thông báo chống CSRF - Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by phatleework7** [UEHMonQAQC/23_902#70]
a. Web browser:  Chrome/ version: 114.0.0.0
b. Các bước phát hiện lỗi:
i. #1: Mở trình duyệt [https://khdtkt.ueh.edu.vn/](url)
ii. #2: Mở F12 để bật Dev Tool kiểm tra thanh tìm kiếm 
iii. #3: Nhập từ khóa vào thanh tìm kiếm sau đó kiểm tra Dev Tool.
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/e8bce438-85b4-4df2-9591-049fa095fe3a)

iv. #4:  Vào app OWASP ZAP kiểm tra lại lần nữa. Nhập tên trang web vào chọn attack
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/925468e8-a068-4bf3-a1ea-c5f70b265a0b)

v. #5: Phát hiện lỗi 
![image](https://github.com/UEHMonQAQC/23_902/assets/141992022/206b099b-b09d-4112-9e17-f229c915e8f7)

c. Kết quả thực tế: Không tìm thấy mã thông báo Anti-CSRF nào 
d. Kết quả mong muốn: Có mã Anti-CSRF để không để hacker dựa trên thanh tìm kiếm để không thể qua CSRF mà thay đổi thông tin cá nhân của người dùng, thay đổi mật khẩu, hoặc thực hiện các hành động khác

**Comment by 31211027598** [comment]
@31211027599 Như thầy nói thì lỗi này là dùng công cụ tool để tìm ra lỗi phi chức năng, nên không được tính là lỗi.
