### ISSUE TITLE
[Nhóm#08] - Lỗi giao diện - Tràn chữ - trang https://shop.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027580** [UEHMonQAQC/23_902#72]
A. Web Browser: GoogleChrome 116.0.5845.111
B. Các bước thục hiện lỗi
i. Truy cập vào trang https://shop.ueh.edu.vn/gioi-thieu/ ở kích thước 390x844 pixel (iPhone 12 pro)
![image](https://github.com/UEHMonQAQC/23_902/assets/142574592/21552016-0cf7-4437-9d95-c43a2fb96956)

C. Kết quả thực tế: Chữ bị tràn ra ngoài khung giới thiệu
D. Kết quả mong đợi: Chữ nằm gọn trong khung giới thiệu.

**Comment by 31211027613** [comment]
Lỗi này đã có trước đó rồi nha nhóm ơi. Link lỗi: https://github.com/UEHMonQAQC/23_902/issues/62
