### ISSUE TITLE
[Nhóm#04] - Lỗi phi chức năng - Lỗi Path Traversal - Trang https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027574** [UEHMonQAQC/23_902#75]
a. Trình duyệt web: Google Chrome phiên bản 116.0.5845.111 - Laptop: MSI Bravo 15 B5DD - Hệ điều hành: Windows 11
b. Kết quả thực tế: Phát hiện ra lỗi SQL Injection
c. Kết quả mong muốn: Không phát hiện ra lỗi SQL Injection
d. Các bước phát hiện lỗi:
**(Lưu ý: Do web có độ bảo mật thấp nên mỗi lần test thì web sẽ sập tầm 1-1.5h)**
i. #1 Mở phần mềm OWASP ZAP như giao diện dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/de17a45b-c7de-4ccf-a47c-2114eedfd370)
Sau đó, ở mục "Welcome to OWASP ZAP", nhấn nút "Automated Scan", giao diện mới mở ra như ở dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/5fe3b91c-1ff2-4eb3-b425-8a56f50f4bc8)
ii. #2 Điền các thông tin như hình dưới đây:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/71c0ee5b-ab14-4b40-a0ef-e36196e5e583)
iii. #3 Nhấn nút "Attack" (có hình sấm sét ở nút đó) rồi chờ một lúc (tầm 20-30p) kết quả sẽ hiện ra:
![image](https://github.com/UEHMonQAQC/23_902/assets/142075662/3d2d49f6-e4a3-4642-a12a-204031799cb4)

**Comment by 31211027582** [comment]
Như thầy đã nói thì đây chỉ là công cụ. Cần tự thực hiện các thao tác của kiểu tấn công này (trải nghiệm thực tế).
