### ISSUE TITLE
[Nhóm#04] - Lỗi giao diện - Lỗi giao diện bị đè lên nhau khi phóng to trang 175% - Trang https://caythuoc.vn/

### ISSUE THREAD

**Issue by 31211027596** [UEHMonQAQC/23_902#79]
a. Web Browser: Google chrome Version 116.0.5845.111 - Hệ điều hành: Windows 11
b.Kết quả thực tế: Khi phóng to trang 175%, ô tìm kiếm và giỏ hàng bị đè lên nhau
c. Kết quả mong muốn: Khi phóng to trang 175%, ô tìm kiếm và giỏ hàng được chia khoảng cách hợp lý
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang https: https://caythuoc.vn/
<img width="960" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/a9d88246-d2bd-4b04-979e-24b9132ba42a">
ii. #1 Phóng to trang lên 175% và quan sát ô tìm kiếm và giỏ hàng
<img width="958" alt="image" src="https://github.com/UEHMonQAQC/23_902/assets/142060841/87b5802e-0240-4eb7-8d62-d8fd12794689">

**Comment by 31211027582** [comment]
Không được dùng chức năng zoom của trình duyệt để check lỗi Gui.
