### ISSUE TITLE
[Nhóm#07] - Lỗi GUI - Lỗi che thông tin khi thực hiện scroll up down liên tục- Trang https://khdtkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31211027623** [UEHMonQAQC/23_902#83]
a. Web Browser: Google Chrome Phiên bản 116.0.5845.111 (Phiên bản Chính thức) (64 bit).
b. Các bước để phát hiện lỗi:
i. #1: Chọn trình duyệt và đăng nhập vào https://khdtkt.ueh.edu.vn/ 
ii. #2: Nhấn vào mục **“Quy trình”** trong mục lục **“QUY TRÌNH - BIỂU MẪU”**.
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/d8d9c56a-015a-47f8-961c-139e8385e006)
iii. #3: Nhấn vào phần “KHĐTKT.QT.21_Quy trình tổ chức kỳ thi chứng chỉ ứng dụng CNTT cơ bản”.
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/b55bed07-5347-49ec-968e-db3d66e426f7)
iiii. #4: scroll up down nhanh ở ngoài box chứa văn bản. Lỗi xuất hiện làm nhấp nháy thông tin:
![image](https://github.com/UEHMonQAQC/23_902/assets/142388914/1f234816-12ee-4228-8447-0b1ab63e59c3)
c. Kết quả thực tế: Phần nội dung bên trong box bị xám, che thông tin.
d. Kết quả mong đợi: không bị lỗi xám và che thông tin, tránh việc gây khó chịu cho người dùng.

**Comment by 31211027598** [comment]
@31211027623 
Trên máy tính của mình test thì không thấy lỗi như trên.

https://drive.google.com/drive/u/0/search?q=type:video
