### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng - Lỗi đăng nhập bằng facebook khi bình luận - trang http://www. http://baolamdong.vn

### ISSUE THREAD

**Issue by 33221025298** [UEHMonQAQC/23_902#85]
a. Web Browser: Goodle Chrome Version 116.
b.Kết quả thực tế: Nhấn gửi bình luận hiển thị hộp thoại không thể đăng nhập bằng facebook
c. Kết quả mong muốn: Đăng nhập được bằng facebook để bình luận hoặc không hiển thị hộp thoại này khi nhấn gửi bình luận nữa
i. #1Truy cập trang http://www/. http://baolamdong.vn/ vào Chọn bài báo bất kỳ, bình luận và gửi bình luận
<img width="915" alt="Screenshot 2023-08-29 080804" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/9b82147e-3060-40d4-9850-4feb806a80d9">
ii. #2 Hộp thoại liên kết với facebook hiện ra và bị lỗi
<img width="837" alt="Screenshot 2023-08-29 080841" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/74374925-46a4-449a-b16b-ce2509ecc955">
<img width="412" alt="Screenshot 2023-08-29 080700" src="https://github.com/UEHMonQAQC/23_902/assets/143202929/3dfcf31f-b96b-48c4-aa48-16eb50c476ca">

**Comment by 31211027582** [comment]
Trùng lỗi #3
