### ISSUE TITLE
[Nhóm#09] - Lỗi phi chức năng  - Lỗi clickjacking- trang ueh.edu.vn

### ISSUE THREAD

**Issue by newbiecode123456** [UEHMonQAQC/23_902#87]
**Web Browser:**
Không sử dụng
**Các bước phát hiện lỗi:**
Bước 1: Sử dụng công cụ quét lỗ hổng website Nikto
Bước 2: Mở công cụ quét lỗ hổng website Nikto, thực hiện quét trang https://ueh.edu.vn
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/6a1c8427-100f-4ab8-8014-22ccf14aadc7)
Bước 3: xác nhận thông tin lỗi từ google
Clickjacking là một hình thức tấn công đánh lừa người dùng nhấp chuột vô ý vào một đối tượng trên website. Khi nhấp chuột vào một đối tượng trên màn hình, người dùng nghĩ là mình đang click vào đối tượng đó nhưng thực chất họ đang bị lừa click vào một đối tượng khác đã bị làm mờ hay ẩn đi. Kẻ tấn công có thể sử dụng kỹ thuật tấn công này cho nhiều mục đích. Đánh cắp tài khoản người dùng, lừa click vào quảng cáo để kiếm tiền, lừa like page hoặc nguy hiểm hơn là cài một webshell lên máy chủ web.
**Kết quả thực tế**
Report báo thiếu header anti hijacking
**Kết quả mong đợi**
Report không trả kết qủa

**Comment by tquann286** [comment]
Chỉ dừng lại ở mức số liệu hoặc cảnh báo, không có minh chứng khai thác thành công hoặc không rõ ràng
