### ISSUE TITLE
[Nhóm#09] - Lỗi phi chức năng - Lỗi XSS- trang ueh.edu.vn

### ISSUE THREAD

**Issue by newbiecode123456** [UEHMonQAQC/23_902#88]
**Web Browser:**
Không sử dụng
**Các bước phát hiện lỗi:**
Bước 1: Sử dụng công cụ quét lỗ hổng website Nikto
Bước 2: Mở công cụ quét lỗ hổng website Nikto, thực hiện quét trang https://ueh.edu.vn
![image](https://github.com/UEHMonQAQC/23_902/assets/117134782/ab2f9323-4571-43a8-89c0-f6ede42b3474)
Bước 3: xác nhận thông tin lỗi từ google
Cross-site scripting – XSS là một kỹ thuật tấn công bảo mật các trang web nhằm mục đích xâm phạm vào nội dung website với tư cách người dùng để truy cập và đánh cắp dữ liệu. Nếu hacker lấy được các quyền truy cập riêng tư trong ứng dụng thì mọi chức năng và dữ liệu đều được khai thác toàn bộ.
**Kết quả thực tế**
Report báo lỗi xss
**Kết quả mong đợi**
Report không trả kết qủa

**Comment by tquann286** [comment]
- Theo như phần mềm Nikto quét được thì trang web này chỉ is **vulnerable** to XSS, tức là dễ bị tấn công bởi xss
- Mình cần 1 vd cụ thể hơn để chứng minh trang web này thật sự có thể bị tấn công bởi xss, vd như bạn đăng nhập vào trang và thực hiện hành động nào đó cho thấy web đã bị tấn công bởi XSS như ví dụ trong slide
@newbiecode123456

[QAQC.zip](https://github.com/UEHMonQAQC/23_902/files/12475410/QAQC.zip)
