### ISSUE TITLE
[Nhóm#06] - Lỗi giao diện - Văn bản viết in hoa, viết thường không đồng đều - trang http://www.http://yame.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#91]
a. Web Browser: Google Chrome Version 116.0.5845.111
b. Các bước phát hiện lỗi:
i. #1: Truy cập trang yame.vn sau đó trỏ chuột vào mục Bộ sưu tập.

![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/ac13ebdf-8910-4ba3-bb36-c3483aad46d5)

c. Kết quả thực tế: Chữ viết thường chữ viết in hoa không đồng nhất.
d. Kết quả mong đợi: Văn bản viết in hoa, viết thường đồng nhất.

**Comment by 31211027613** [comment]
Mình nghĩ đây giống như là chủ ý của bên trang web hơn là lỗi ạ
