### ISSUE TITLE
[Nhóm#06] - Lỗi giao diện - Lỗi căn chỉnh ảnh không đều- trang http://www.http://yame.vn

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/23_902#99]
a. Web Browser: Google Chrome Version 116.0.5845.111
b. Các bước phát hiện lỗi 
i. #1:Truy cập website Yame.vn và nhấp vào mục Giới thiệu về Yame.vn dưới cùng
![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/b73725c4-7cda-483b-9be3-5e326cb9cf26)

ii. #2: Cuộn xuống một đoạn sẽ thấy hình ảnh không đều 
![image](https://github.com/UEHMonQAQC/23_902/assets/142565645/62732b28-b24b-4d39-8665-871cf1ac4934)

c. Kết quả thực tế: Ảnh căn chỉnh không đồng đều
d. Kết quả mong đợi: Ảnh căn chỉnh đồng đều không bị lệch

**Comment by 31211027613** [comment]
Mình nghĩ mặc định căn lề của trang web là về bên trái. Nên việc lỗi căn chỉnh này mình nghĩ không phải là lỗi, việc căn lề sang trái nhiều hay ít là do kích thước của ảnh ạ
